"""Build BTC Wheel Bot reconstruction notebook - Phase 0-4."""
import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell

nb = new_notebook()
cells = []

def md(source): cells.append(new_markdown_cell(source))
def code(source): cells.append(new_code_cell(source))

# TITLE
md("""# BTC Wheel Bot - Complete Reconstruction Guide

**13 Phases, ~230 Steps**

Run cells top-to-bottom in a fresh project directory. Each step does one thing and includes verification.

## Architecture Summary

| Module | Role |
|--------|------|
| `config.py` / `config.yaml` | All configuration, typed dataclasses |
| `deribit_client.py` | Deribit REST + WebSocket wrapper |
| `strategy.py` | IV rank, strike selection, wheel cycle logic |
| `risk_manager.py` | Position sizing, kill-switch, drawdown checks |
| `bot.py` | 60-second async main loop (paper + live) |
| `main.py` | CLI entry point (backtest/paper/testnet/live) |
| `backtester.py` | Black-Scholes historical simulation |
| `optimizer.py` | Genetic algorithm over all parameters |
| `config_store.py` | Named config CRUD + lifecycle management |
| `bot_farm.py` | Supervisor for parallel paper-trading bots |
| `readiness_validator.py` | 8-check go/no-go for live promotion |
| `api.py` | FastAPI backend (mobile app talks here) |
| `notifier.py` | Telegram alerts |
| `hedge_manager.py` | Delta-neutral BTC-PERP hedge |
| `ai_overseer.py` | LLM safety layer (halt-only, fail-open) |

## How the Wheel Works

1. **Sell a cash-secured put** (delta ~0.20-0.40, OTM) - collect premium
   - BTC stays above strike: option expires worthless, keep premium
   - BTC falls below strike: option expires ITM (cash-settled on Deribit)
2. **Sell a covered call** after put cycle completes
   - Normal OTM put: sell call at delta ~0.25
   - ITM put ("recovery"): sell call at or ABOVE put strike to capture BTC recovery
3. Repeat: put -> call -> put -> ...

**Key filters:** IV rank threshold, dynamic delta scaling, regime MA filter, ladder mode
""")

# PHASE 0
md("## Phase 0: Prerequisites & Project Setup (Steps 1-12)")

md("### Step 1 - Create project directory structure\n\nAll bot files live in one flat directory. Subdirectories: `data/`, `logs/`, `configs/`, `farm/`, `mobile-app/`.")
code("""import os, pathlib

PROJECT = pathlib.Path("/root/Documents/btc-wheel-bot")
for d in ["data", "data/optimizer", "logs", "configs", "farm", "mobile-app/src/components"]:
    (PROJECT / d).mkdir(parents=True, exist_ok=True)

print("Created:", PROJECT)
print("Subdirs:", sorted([d.name for d in PROJECT.iterdir() if d.is_dir()]))
""")

md("### Step 2 - Check Python version (needs 3.10+)")
code("""import sys
v = sys.version_info
print(f"Python {v.major}.{v.minor}.{v.micro}")
assert v >= (3, 10), f"Need Python 3.10+, got {v.major}.{v.minor}"
print("OK - Python version requirement met")
""")

md("### Step 3 - Install Python dependencies")
code("""!pip install -q \\
    aiohttp>=3.9.0 websockets>=12.0 requests>=2.31.0 \\
    pandas>=2.0.0 numpy>=1.26.0 scipy>=1.12.0 \\
    matplotlib>=3.8.0 tabulate>=0.9.0 \\
    pyyaml>=6.0.1 python-dotenv>=1.0.0 \\
    loguru>=0.7.2 \\
    fastapi>=0.111.0 "uvicorn[standard]>=0.30.0" httpx pydantic
print("Dependencies installed")
""")

md("### Step 4 - Node.js check (for mobile-app build, needs Node 20+)")
code("""import subprocess
r = subprocess.run(["node", "--version"], capture_output=True, text=True)
print("node:", r.stdout.strip() or "NOT FOUND - install from nodejs.org")
r2 = subprocess.run(["npm", "--version"], capture_output=True, text=True)
print("npm:", r2.stdout.strip() or "NOT FOUND")
""")

md("""### Step 5 - Create `.env` file template

Secrets come ONLY from environment variables, NEVER from `config.yaml`.

- `DERIBIT_API_KEY` / `DERIBIT_API_SECRET` - from https://www.deribit.com/account/api
- `DERIBIT_TESTNET` - `true` for test.deribit.com, `false` for mainnet
- `WHEEL_API_KEY` - auto-generated by `api.py` on first run (32-char hex)
- `LOG_LEVEL` - DEBUG | INFO | WARNING | ERROR (default: INFO)
""")
code("""env_example = '''# Deribit Credentials
# Get from: https://www.deribit.com/account/api
# NEVER commit real credentials to version control.
DERIBIT_API_KEY=your_api_key_here
DERIBIT_API_SECRET=your_api_secret_here

# Use testnet for development (overrides config.yaml deribit.testnet)
DERIBIT_TESTNET=true

# Mobile API - auto-generated by api.py on first run
WHEEL_API_KEY=

# Optional overrides
LOG_LEVEL=INFO
'''

with open("/root/Documents/btc-wheel-bot/.env.example", "w") as f:
    f.write(env_example)
print("Written: .env.example")
print("Next: cp .env.example .env  and fill in real credentials")
""")

md("### Step 6-8 - Create runtime directories and verify imports")
code("""import os
for d in ["data/optimizer", "logs", "configs", "farm"]:
    os.makedirs(f"/root/Documents/btc-wheel-bot/{d}", exist_ok=True)
print("Runtime dirs ready")
""")

code("""# Verify all required imports work
import asyncio, json, csv, time, math, random, copy, signal
import subprocess, multiprocessing, argparse
import aiohttp, requests
import pandas as pd, numpy as np
from scipy.stats import norm
import matplotlib
import yaml
from dotenv import load_dotenv
from loguru import logger
from fastapi import FastAPI
print("All imports OK")
""")

md("### Step 9 - Create `.gitignore`")
code("""gitignore = """.env
__pycache__/
*.pyc
*.egg-info/
.venv/
venv/
*.log
data/*.csv
data/*.json
data/optimizer/
KILL_SWITCH
*.bak
mobile-app/node_modules/
mobile-app/dist/
farm/
*.png
"""

with open("/root/Documents/btc-wheel-bot/.gitignore", "w") as f:
    f.write(gitignore)
print("Written: .gitignore")
""")

md("""### Steps 10-11 - Initialize git and create GitHub repo (manual)

```bash
cd ~/Documents/btc-wheel-bot
git init
git add config.yaml config.py requirements.txt .env.example .gitignore
git commit -m "Initial commit: BTC wheel bot skeleton"

# Create repo on GitHub (using gh CLI):
gh repo create banksiasprings/btc-wheel-bot --private --source=. --push
```
""")

md("### Step 12 - CHECKPOINT: verify directory structure")
code("""import os
required = ["data", "logs", "configs", "farm", "mobile-app"]
for d in required:
    exists = os.path.isdir(f"/root/Documents/btc-wheel-bot/{d}")
    print(f"  {'OK' if exists else 'MISSING'} {d}/")
assert all(os.path.isdir(f"/root/Documents/btc-wheel-bot/{d}") for d in required)
print("CHECKPOINT PASSED: directory structure is correct")
""")

# PHASE 1
md("## Phase 1: Configuration System (Steps 13-25)")

md("""### Step 13 - Write `config.yaml`

All non-secret configuration. The optimizer evolves these values and saves named configs in `configs/`.

**Key values explained:**
- `iv_rank_threshold: 0.701` - only sell options when IV is in top 30% of its 52-week range
- `target_delta_min/max: 0.1883/0.4057` - delta range for strike selection
- `iv_dynamic_delta: true` - shift target delta with IV rank (high IV = sell closer ATM)
- `max_equity_per_leg: 0.0828` - use 8.28% of equity per position
- `min_free_equity_fraction: 0.1007` - keep 10% of equity free at all times
- `ladder_enabled: false` - single leg mode (set true for 2+ simultaneous puts)
- `use_regime_filter: false` - skip new puts when BTC below N-day MA (set true to enable)
""")
code("""config_yaml = '''backtest:
  approx_otm_offset: 0.0338
  lookback_months: 12
  premium_fraction_of_spot: 0.0289
  results_csv: data/backtest_trades.csv
  results_image: backtest_results.png
  risk_free_rate: 0.04
  starting_equity: 1000.0
  transaction_cost: 0.5
deribit:
  currency: BTC
  request_timeout: 10
  rest_url_mainnet: https://www.deribit.com/api/v2
  rest_url_testnet: https://test.deribit.com/api/v2
  testnet: true
  ws_url_mainnet: wss://www.deribit.com/ws/api/v2
  ws_url_testnet: wss://test.deribit.com/ws/api/v2
execution:
  order_confirm_timeout: 30
  poll_interval: 60
  slippage_tolerance: 0.005
hedge:
  enabled: true
  rebalance_threshold: 0.05
logging:
  level: INFO
  log_dir: logs
  retention: 30 days
  rotation: 1 day
  trade_log_csv: data/trades.csv
overseer:
  check_interval_minutes: 60
  drawdown_warning_threshold: 0.05
  enabled: true
  iv_spike_warning_threshold: 0.85
risk:
  kill_switch_file: KILL_SWITCH
  max_adverse_delta: 0.4
  max_daily_drawdown: 0.1
  max_loss_per_leg: 0.02
  roll_enabled: false
  roll_min_dte: 3
sizing:
  collateral_buffer: 1.0
  contract_size_btc: 0.1
  ladder_enabled: false
  ladder_legs: 2
  max_equity_per_leg: 0.0828
  max_open_legs: 1
  min_free_equity_fraction: 0.1007
  regime_ma_days: 50
  use_regime_filter: false
strategy:
  expiry_execution_hour: 8
  expiry_preference:
  - weekly
  - monthly
  initial_cycle: put
  iv_dynamic_delta: true
  iv_rank_threshold: 0.701
  liquidity_top_n: 100
  max_dte: 37
  min_dte: 3
  target_delta_max: 0.4057
  target_delta_min: 0.1883
'''

with open("/root/Documents/btc-wheel-bot/config.yaml", "w") as f:
    f.write(config_yaml)
print("Written: config.yaml")
""")

md("### Step 14 - Write `config.py`\n\nTyped dataclasses for every config section. The `cfg` singleton is imported by every other module. **Rule: secrets come ONLY from `os.getenv()`, never from YAML.**")
code(r"""config_py = '''"""
config.py - Centralised configuration loader for BTC Wheel Bot.

Loads settings from config.yaml, then overlays values from environment
variables (via .env or system env). Exposes a single typed Config object
that every other module imports.

Usage:
    from config import cfg
    print(cfg.strategy.iv_rank_threshold)
"""

from __future__ import annotations
import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal
import yaml
from dotenv import load_dotenv

load_dotenv()


@dataclass
class DeribitConfig:
    testnet: bool
    ws_url_testnet: str
    ws_url_mainnet: str
    rest_url_testnet: str
    rest_url_mainnet: str
    request_timeout: int
    currency: str
    api_key: str = ""
    api_secret: str = ""

    @property
    def ws_url(self) -> str:
        return self.ws_url_testnet if self.testnet else self.ws_url_mainnet

    @property
    def rest_url(self) -> str:
        return self.rest_url_testnet if self.testnet else self.rest_url_mainnet


@dataclass
class StrategyConfig:
    iv_rank_threshold: float
    target_delta_min: float
    target_delta_max: float
    expiry_preference: list[str]
    min_dte: int
    max_dte: int
    initial_cycle: Literal["put", "call"]
    expiry_execution_hour: int
    liquidity_top_n: int
    iv_dynamic_delta: bool = False


@dataclass
class SizingConfig:
    max_equity_per_leg: float
    max_open_legs: int
    collateral_buffer: float
    contract_size_btc: float
    min_free_equity_fraction: float = 0.25
    use_regime_filter: bool = False
    regime_ma_days: int = 50
    ladder_enabled: bool = False
    ladder_legs: int = 2


@dataclass
class RiskConfig:
    max_adverse_delta: float
    max_loss_per_leg: float
    max_daily_drawdown: float
    kill_switch_file: str
    roll_enabled: bool = False
    roll_min_dte: int = 3


@dataclass
class ExecutionConfig:
    poll_interval: int
    order_confirm_timeout: int
    slippage_tolerance: float


@dataclass
class BacktestConfig:
    starting_equity: float
    lookback_months: int
    transaction_cost: float
    approx_otm_offset: float
    premium_fraction_of_spot: float
    risk_free_rate: float
    results_image: str
    results_csv: str


@dataclass
class HedgeConfig:
    enabled: bool = True
    rebalance_threshold: float = 0.05


@dataclass
class OverseerConfig:
    enabled: bool
    check_interval_minutes: int
    drawdown_warning_threshold: float
    iv_spike_warning_threshold: float


@dataclass
class LoggingConfig:
    level: str
    rotation: str
    retention: str
    log_dir: str
    trade_log_csv: str


@dataclass
class Config:
    deribit: DeribitConfig
    strategy: StrategyConfig
    sizing: SizingConfig
    risk: RiskConfig
    execution: ExecutionConfig
    backtest: BacktestConfig
    overseer: OverseerConfig
    logging: LoggingConfig
    hedge: HedgeConfig = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.hedge is None:
            self.hedge = HedgeConfig()


def _load_yaml(path: Path) -> dict:
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")
    with open(path) as fh:
        return yaml.safe_load(fh) or {}


def load_config(yaml_path=None) -> Config:
    """
    Load configuration from YAML + env var overrides.
    WHEEL_BOT_CONFIG env var overrides the default config.yaml path.
    WHEEL_BOT_DATA_DIR env var redirects all data file paths (used by bot farm).
    """
    if yaml_path is None:
        config_path = os.environ.get("WHEEL_BOT_CONFIG", None)
        if config_path:
            yaml_path = Path(config_path)
        else:
            yaml_path = Path(__file__).parent / "config.yaml"

    raw = _load_yaml(Path(yaml_path))

    d = raw["deribit"]
    deribit_cfg = DeribitConfig(
        testnet=os.getenv("DERIBIT_TESTNET", str(d["testnet"])).lower() == "true",
        ws_url_testnet=d["ws_url_testnet"],
        ws_url_mainnet=d["ws_url_mainnet"],
        rest_url_testnet=d["rest_url_testnet"],
        rest_url_mainnet=d["rest_url_mainnet"],
        request_timeout=int(d["request_timeout"]),
        currency=d["currency"],
        api_key=os.getenv("DERIBIT_API_KEY", ""),    # NEVER from YAML
        api_secret=os.getenv("DERIBIT_API_SECRET", ""),  # NEVER from YAML
    )

    s = raw["strategy"]
    strategy_cfg = StrategyConfig(
        iv_rank_threshold=float(s["iv_rank_threshold"]),
        target_delta_min=float(s["target_delta_min"]),
        target_delta_max=float(s["target_delta_max"]),
        expiry_preference=list(s["expiry_preference"]),
        min_dte=int(s["min_dte"]),
        max_dte=int(s["max_dte"]),
        initial_cycle=s["initial_cycle"],
        expiry_execution_hour=int(s["expiry_execution_hour"]),
        liquidity_top_n=int(s["liquidity_top_n"]),
        iv_dynamic_delta=bool(s.get("iv_dynamic_delta", False)),
    )

    sz = raw["sizing"]
    sizing_cfg = SizingConfig(
        max_equity_per_leg=float(sz["max_equity_per_leg"]),
        max_open_legs=int(sz["max_open_legs"]),
        collateral_buffer=float(sz["collateral_buffer"]),
        contract_size_btc=float(sz["contract_size_btc"]),
        min_free_equity_fraction=float(sz.get("min_free_equity_fraction", 0.25)),
        use_regime_filter=bool(sz.get("use_regime_filter", False)),
        regime_ma_days=int(sz.get("regime_ma_days", 50)),
        ladder_enabled=bool(sz.get("ladder_enabled", False)),
        ladder_legs=int(sz.get("ladder_legs", 2)),
    )

    r = raw["risk"]
    risk_cfg = RiskConfig(
        max_adverse_delta=float(r["max_adverse_delta"]),
        max_loss_per_leg=float(r["max_loss_per_leg"]),
        max_daily_drawdown=float(r["max_daily_drawdown"]),
        kill_switch_file=r["kill_switch_file"],
        roll_enabled=bool(r.get("roll_enabled", False)),
        roll_min_dte=int(r.get("roll_min_dte", 3)),
    )

    e = raw["execution"]
    exec_cfg = ExecutionConfig(
        poll_interval=int(e["poll_interval"]),
        order_confirm_timeout=int(e["order_confirm_timeout"]),
        slippage_tolerance=float(e["slippage_tolerance"]),
    )

    bt = raw["backtest"]
    backtest_cfg = BacktestConfig(
        starting_equity=float(bt["starting_equity"]),
        lookback_months=int(bt["lookback_months"]),
        transaction_cost=float(bt["transaction_cost"]),
        approx_otm_offset=float(bt["approx_otm_offset"]),
        premium_fraction_of_spot=float(bt["premium_fraction_of_spot"]),
        risk_free_rate=float(bt["risk_free_rate"]),
        results_image=bt["results_image"],
        results_csv=bt["results_csv"],
    )

    ov = raw.get("overseer", {})
    overseer_cfg = OverseerConfig(
        enabled=bool(ov.get("enabled", True)),
        check_interval_minutes=int(ov.get("check_interval_minutes", 60)),
        drawdown_warning_threshold=float(ov.get("drawdown_warning_threshold", 0.05)),
        iv_spike_warning_threshold=float(ov.get("iv_spike_warning_threshold", 0.85)),
    )

    lg = raw["logging"]
    logging_cfg = LoggingConfig(
        level=os.getenv("LOG_LEVEL", lg["level"]),
        rotation=lg["rotation"],
        retention=lg["retention"],
        log_dir=lg["log_dir"],
        trade_log_csv=lg["trade_log_csv"],
    )

    hg = raw.get("hedge", {})
    hedge_cfg = HedgeConfig(
        enabled=bool(hg.get("enabled", True)),
        rebalance_threshold=float(hg.get("rebalance_threshold", 0.05)),
    )

    cfg_obj = Config(
        deribit=deribit_cfg, strategy=strategy_cfg, sizing=sizing_cfg,
        risk=risk_cfg, execution=exec_cfg, backtest=backtest_cfg,
        overseer=overseer_cfg, logging=logging_cfg, hedge=hedge_cfg,
    )

    # Farm isolation: redirect data file paths when WHEEL_BOT_DATA_DIR is set
    data_dir = os.environ.get("WHEEL_BOT_DATA_DIR", None)
    if data_dir:
        cfg_obj.logging.trade_log_csv = os.path.join(
            data_dir, os.path.basename(cfg_obj.logging.trade_log_csv))
        cfg_obj.logging.log_dir = os.path.join(data_dir, "logs")
        cfg_obj.backtest.results_csv = os.path.join(
            data_dir, os.path.basename(cfg_obj.backtest.results_csv))
        cfg_obj.backtest.results_image = os.path.join(
            data_dir, os.path.basename(cfg_obj.backtest.results_image))
        cfg_obj.risk.kill_switch_file = os.path.join(
            data_dir, os.path.basename(cfg_obj.risk.kill_switch_file))

    return cfg_obj


# Module-level singleton - import this everywhere
cfg: Config = load_config()
'''

with open("/root/Documents/btc-wheel-bot/config.py", "w") as f:
    f.write(config_py)
print("Written: config.py")
""")

md("### Step 15 - Test config loads without errors")
code("""import sys, os
sys.path.insert(0, "/root/Documents/btc-wheel-bot")
os.chdir("/root/Documents/btc-wheel-bot")

# Force reload in case previously imported
import importlib
if 'config' in sys.modules:
    del sys.modules['config']

from config import cfg
print(f"iv_rank_threshold : {cfg.strategy.iv_rank_threshold}")
print(f"target_delta_min  : {cfg.strategy.target_delta_min}")
print(f"target_delta_max  : {cfg.strategy.target_delta_max}")
print(f"max_equity_per_leg: {cfg.sizing.max_equity_per_leg}")
print(f"testnet           : {cfg.deribit.testnet}")
print(f"hedge.enabled     : {cfg.hedge.enabled}")
assert cfg.strategy.iv_rank_threshold == 0.701
assert cfg.sizing.max_open_legs == 1
assert cfg.deribit.currency == "BTC"
print("CHECKPOINT: Config system OK")
""")

# PHASE 2
md("## Phase 2: Deribit API Client (Steps 16-25)")

md("""### Step 16 - Deribit API structure

**Two environments:**
- Testnet: `test.deribit.com` (fake BTC, real API, use for all development)
- Mainnet: `www.deribit.com` (real BTC, only for live trading)

**Three interfaces:**
1. **Public REST** (`/api/v2/public/...`) - No auth. Used by backtester and strategy for instruments, tickers, historical IV, OHLCV.
2. **Private REST** (`/api/v2/private/...`) - OAuth2 client_credentials token. Used for: account summary, open positions, cancel orders. Token auto-refreshes before expiry.
3. **WebSocket** (`wss://...`) - Async, real-time. Used for: order placement (`private/sell`, `private/buy`), settlement subscriptions (`user.changes.any.BTC.raw`).

**Instrument naming:** `BTC-25APR25-90000-P` = BTC, expiry 25 Apr 2025, strike $90k, Put.
Options expire at 08:00 UTC. Settlement is cash (no BTC delivery).

**Rate limits:** Public REST ~20 req/sec. Ticker fetching is the bottleneck (900+ instruments). Pre-filter by DTE before fetching tickers.
""")

md("### Step 17 - Write `deribit_client.py`")
code(r"""deribit_client_py = '''"""
deribit_client.py - Deribit REST + WebSocket client.

Public endpoints (no auth) are used for backtest mode.
DeribitPrivateREST uses OAuth2 client_credentials for authenticated
account queries (positions, equity, settlements).
DeribitWebSocket handles real-time data, order execution, and settlement
event subscriptions for live/paper mode.

All live order methods are marked # LIVE_ONLY.
"""

from __future__ import annotations
import asyncio
import json
import time
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Callable

import aiohttp
import requests
from loguru import logger

from config import cfg


@dataclass
class Ticker:
    instrument_name: str
    mark_price: float
    bid: float
    ask: float
    mark_iv: float        # implied volatility (annualised %)
    delta: float
    gamma: float
    theta: float
    vega: float
    underlying_price: float
    timestamp: datetime
    greeks: dict | None = None


@dataclass
class Instrument:
    instrument_name: str
    strike: float
    expiry_ts: int        # Unix timestamp ms
    option_type: str      # "put" | "call"
    dte: int              # days to expiry


@dataclass
class AccountSummary:
    equity: float          # total account equity in BTC
    balance: float
    available_funds: float
    margin_balance: float
    currency: str = "BTC"


@dataclass
class ExchangePosition:
    """Open position as reported by Deribit (live mode)."""
    instrument_name: str
    size: float            # positive = long, negative = short
    direction: str         # "buy" | "sell"
    average_price: float
    mark_price: float
    floating_profit_loss: float
    delta: float
    option_type: str       # "put" | "call"
    expiry_ts: int


class DeribitPublicREST:
    """Thin wrapper around Deribit public REST API (no authentication)."""

    BASE_URL = "https://www.deribit.com/api/v2/public"

    def __init__(self, timeout: int = 10) -> None:
        self.timeout = timeout
        self.session = requests.Session()
        self.session.headers["Accept"] = "application/json"

    def _get(self, method: str, params: dict | None = None) -> Any:
        url = f"{self.BASE_URL}/{method}"
        try:
            resp = self.session.get(url, params=params, timeout=self.timeout)
            resp.raise_for_status()
            data = resp.json()
            if "result" not in data:
                raise ValueError(f"Unexpected response: {data}")
            return data["result"]
        except requests.RequestException as exc:
            logger.error(f"REST error [{method}]: {exc}")
            raise

    def get_instruments(self, currency: str = "BTC", kind: str = "option",
                        expired: bool = False) -> list[Instrument]:
        """Fetch all active options instruments for a currency."""
        raw = self._get("get_instruments", {
            "currency": currency, "kind": kind, "expired": str(expired).lower(),
        })
        instruments: list[Instrument] = []
        now_ts = int(time.time() * 1000)
        for item in raw:
            dte = max(0, (item["expiration_timestamp"] - now_ts) // 86_400_000)
            instruments.append(Instrument(
                instrument_name=item["instrument_name"],
                strike=float(item["strike"]),
                expiry_ts=item["expiration_timestamp"],
                option_type=item["option_type"],
                dte=dte,
            ))
        logger.debug(f"Fetched {len(instruments)} instruments for {currency}")
        return instruments

    def get_ticker(self, instrument_name: str) -> Ticker | None:
        """Fetch current ticker + Greeks for a single instrument."""
        try:
            raw = self._get("ticker", {"instrument_name": instrument_name})
            greeks_raw = raw.get("greeks", {})
            return Ticker(
                instrument_name=instrument_name,
                mark_price=float(raw.get("mark_price", 0)),
                bid=float(raw.get("best_bid_price", 0)),
                ask=float(raw.get("best_ask_price", 0)),
                mark_iv=float(raw.get("mark_iv", 0)),
                delta=float(greeks_raw.get("delta", 0)),
                gamma=float(greeks_raw.get("gamma", 0)),
                theta=float(greeks_raw.get("theta", 0)),
                vega=float(greeks_raw.get("vega", 0)),
                underlying_price=float(raw.get("underlying_price", 0)),
                timestamp=datetime.fromtimestamp(raw["timestamp"] / 1000, tz=timezone.utc),
                greeks=greeks_raw,
            )
        except Exception as exc:
            logger.warning(f"Could not fetch ticker for {instrument_name}: {exc}")
            return None

    def get_historical_volatility(self, currency: str = "BTC") -> list[tuple[int, float]]:
        """Fetch historical daily IV. Returns list of (timestamp_ms, iv_value) tuples."""
        raw = self._get("get_historical_volatility", {"currency": currency})
        return [(int(row[0]), float(row[1])) for row in raw]

    def get_tradingview_chart_data(self, instrument_name: str, resolution,
                                    start_timestamp: int, end_timestamp: int) -> list[dict]:
        """Fetch OHLCV data from Deribit TradingView endpoint."""
        raw = self._get("get_tradingview_chart_data", {
            "instrument_name": instrument_name,
            "start_timestamp": start_timestamp * 1000,
            "end_timestamp": end_timestamp * 1000,
            "resolution": str(resolution),
        })
        if not raw or raw.get("status") == "no_data":
            return []
        ticks = raw.get("ticks", [])
        return [
            {"timestamp": ticks[i], "open": raw["open"][i], "high": raw["high"][i],
             "low": raw["low"][i], "close": raw["close"][i], "volume": raw["volume"][i]}
            for i in range(len(ticks))
        ]


class DeribitPrivateREST:
    """
    Authenticated REST client using OAuth2 client_credentials flow.
    Token auto-refreshes 30s before expiry (tokens last ~15 minutes).
    Requires DERIBIT_API_KEY and DERIBIT_API_SECRET environment variables.
    """

    def __init__(self, api_key: str, api_secret: str, testnet: bool = False,
                 timeout: int = 10) -> None:
        self._api_key = api_key
        self._api_secret = api_secret
        self._timeout = timeout
        self._access_token: str = ""
        self._token_expires_at: float = 0.0
        base = "https://test.deribit.com" if testnet else "https://www.deribit.com"
        self._pub_url = f"{base}/api/v2/public"
        self._priv_url = f"{base}/api/v2/private"
        self.session = requests.Session()
        self.session.headers["Accept"] = "application/json"

    def _authenticate(self) -> None:
        if not self._api_key or not self._api_secret:
            raise ValueError("DERIBIT_API_KEY and DERIBIT_API_SECRET must be set")
        resp = self.session.get(f"{self._pub_url}/auth", params={
            "grant_type": "client_credentials",
            "client_id": self._api_key,
            "client_secret": self._api_secret,
        }, timeout=self._timeout)
        resp.raise_for_status()
        data = resp.json()
        if "error" in data:
            raise RuntimeError(f"Authentication failed: {data['error']}")
        result = data["result"]
        self._access_token = result["access_token"]
        self._token_expires_at = time.time() + result.get("expires_in", 900) - 30
        logger.info("Deribit private REST authenticated (token valid ~15min)")

    def _ensure_auth(self) -> None:
        if time.time() >= self._token_expires_at:
            self._authenticate()

    def _get(self, method: str, params: dict | None = None) -> Any:
        self._ensure_auth()
        url = f"{self._priv_url}/{method}"
        headers = {"Authorization": f"Bearer {self._access_token}"}
        resp = self.session.get(url, params=params or {}, headers=headers,
                                timeout=self._timeout)
        resp.raise_for_status()
        data = resp.json()
        if "error" in data:
            raise RuntimeError(f"Deribit API error [{method}]: {data['error']}")
        return data["result"]

    def get_account_summary(self, currency: str = "BTC") -> AccountSummary:
        raw = self._get("get_account_summary", {"currency": currency})
        return AccountSummary(
            equity=float(raw.get("equity", 0.0)),
            balance=float(raw.get("balance", 0.0)),
            available_funds=float(raw.get("available_funds", 0.0)),
            margin_balance=float(raw.get("margin_balance", 0.0)),
            currency=currency,
        )

    def get_positions(self, currency: str = "BTC", kind: str = "option") -> list[ExchangePosition]:
        raw_list = self._get("get_positions", {"currency": currency, "kind": kind})
        positions: list[ExchangePosition] = []
        for raw in raw_list:
            inst = raw.get("instrument_name", "")
            parts = inst.split("-")
            opt_type = "put" if parts[-1] == "P" else "call"
            try:
                from datetime import datetime as _dt
                expiry_dt = _dt.strptime(parts[1], "%d%b%y").replace(
                    hour=8, minute=0, second=0, tzinfo=timezone.utc)
                expiry_ts = int(expiry_dt.timestamp() * 1000)
            except Exception:
                expiry_ts = 0
            positions.append(ExchangePosition(
                instrument_name=inst,
                size=float(raw.get("size", 0.0)),
                direction=raw.get("direction", "sell"),
                average_price=float(raw.get("average_price", 0.0)),
                mark_price=float(raw.get("mark_price", 0.0)),
                floating_profit_loss=float(raw.get("floating_profit_loss", 0.0)),
                delta=float(raw.get("delta", 0.0)),
                option_type=opt_type,
                expiry_ts=expiry_ts,
            ))
        return positions

    def get_open_orders(self, currency: str = "BTC", kind: str = "option") -> list[dict]:
        return self._get("get_open_orders_by_currency", {"currency": currency, "kind": kind})

    def cancel_order(self, order_id: str) -> dict:
        return self._get("cancel", {"order_id": order_id})

    def cancel_all_by_instrument(self, instrument_name: str) -> int:
        return self._get("cancel_all_by_instrument", {"instrument_name": instrument_name})

    def get_settlement_history_by_instrument(self, instrument_name: str,
                                              settlement_type: str = "settlement",
                                              count: int = 5) -> list[dict]:
        return self._get("get_settlement_history_by_instrument", {
            "instrument_name": instrument_name, "type": settlement_type, "count": count,
        })


class DeribitWebSocket:
    """
    Async WebSocket client for real-time data and order management.
    # LIVE_ONLY - not used in backtest mode.

    JSON-RPC over WebSocket. All requests are async (futures-based).
    Subscription callbacks are called synchronously from the recv loop.
    """

    def __init__(self) -> None:
        self._ws: aiohttp.ClientWebSocketResponse | None = None
        self._session: aiohttp.ClientSession | None = None
        self._msg_id: int = 1
        self._pending: dict[int, asyncio.Future] = {}
        self._authenticated: bool = False
        self._subscriptions: dict[str, Callable[[dict], None]] = {}

    async def connect(self) -> None:
        self._session = aiohttp.ClientSession()
        self._ws = await self._session.ws_connect(cfg.deribit.ws_url)
        asyncio.create_task(self._recv_loop())
        logger.info(f"WebSocket connected to {cfg.deribit.ws_url}")

    async def authenticate(self) -> None:
        if not cfg.deribit.api_key:
            raise ValueError("DERIBIT_API_KEY not set")
        await self._rpc("public/auth", {
            "grant_type": "client_credentials",
            "client_id": cfg.deribit.api_key,
            "client_secret": cfg.deribit.api_secret,
        })
        self._authenticated = True
        logger.info("WebSocket authenticated")

    async def subscribe(self, channels: list[str],
                        callback: Callable[[dict], None]) -> None:
        """Subscribe to private channels. # LIVE_ONLY"""
        if not self._authenticated:
            raise RuntimeError("Must authenticate before subscribing")
        for channel in channels:
            self._subscriptions[channel] = callback
        result = await self._rpc("private/subscribe", {"channels": channels})
        logger.info(f"Subscribed to: {channels}")
        return result

    async def _rpc(self, method: str, params: dict) -> Any:
        msg_id = self._msg_id
        self._msg_id += 1
        loop = asyncio.get_event_loop()
        fut: asyncio.Future = loop.create_future()
        self._pending[msg_id] = fut
        payload = json.dumps({"jsonrpc": "2.0", "id": msg_id, "method": method, "params": params})
        await self._ws.send_str(payload)
        return await asyncio.wait_for(fut, timeout=cfg.execution.order_confirm_timeout)

    async def _recv_loop(self) -> None:
        async for msg in self._ws:
            if msg.type != aiohttp.WSMsgType.TEXT:
                continue
            try:
                data = json.loads(msg.data)
            except json.JSONDecodeError:
                continue
            # Route RPC responses
            if "id" in data and data["id"] in self._pending:
                fut = self._pending.pop(data["id"])
                if "error" in data:
                    fut.set_exception(RuntimeError(data["error"]["message"]))
                else:
                    fut.set_result(data.get("result"))
            # Route subscription push messages
            elif data.get("method") == "subscription":
                params = data.get("params", {})
                channel = params.get("channel", "")
                channel_data = params.get("data", {})
                cb = self._subscriptions.get(channel)
                if cb:
                    try:
                        cb(channel_data)
                    except Exception as exc:
                        logger.error(f"Subscription callback error [{channel}]: {exc}")
                else:
                    for sub_channel, sub_cb in self._subscriptions.items():
                        if channel.startswith(sub_channel.rstrip("*")):
                            try:
                                sub_cb(channel_data)
                            except Exception as exc:
                                logger.error(f"Subscription callback error: {exc}")
                            break

    async def sell_option(self, instrument_name: str, amount: float,
                          order_type: str = "limit", price: float | None = None,
                          label: str = "") -> dict:
        """Sell (short) an option. # LIVE_ONLY"""
        if not self._authenticated:
            raise RuntimeError("Must authenticate before placing orders")
        params: dict = {"instrument_name": instrument_name, "amount": amount,
                        "type": order_type, "label": label}
        if price is not None:
            params["price"] = price
        result = await self._rpc("private/sell", params)
        logger.info(f"Sell order placed: {instrument_name} x{amount} @ {price}")
        return result

    async def buy_option(self, instrument_name: str, amount: float,
                         order_type: str = "limit", price: float | None = None,
                         label: str = "") -> dict:
        """Buy to close a short position. # LIVE_ONLY"""
        if not self._authenticated:
            raise RuntimeError("Must authenticate before placing orders")
        params: dict = {"instrument_name": instrument_name, "amount": amount,
                        "type": order_type, "label": label}
        if price is not None:
            params["price"] = price
        result = await self._rpc("private/buy", params)
        logger.info(f"Buy-to-close order placed: {instrument_name} x{amount} @ {price}")
        return result

    async def close(self) -> None:
        if self._ws and not self._ws.closed:
            await self._ws.close()
        if self._session and not self._session.closed:
            await self._session.close()
        logger.info("WebSocket connection closed")


class DeribitClient:
    """Unified client: public REST, private REST, WebSocket."""

    def __init__(self) -> None:
        self.rest = DeribitPublicREST(timeout=cfg.deribit.request_timeout)
        self.ws: DeribitWebSocket | None = None
        self._private: DeribitPrivateREST | None = None
        if cfg.deribit.api_key and cfg.deribit.api_secret:
            self._private = DeribitPrivateREST(
                api_key=cfg.deribit.api_key,
                api_secret=cfg.deribit.api_secret,
                testnet=cfg.deribit.testnet,
                timeout=cfg.deribit.request_timeout,
            )
            logger.info("DeribitPrivateREST initialised (API keys found)")
        else:
            logger.info("No API keys - public-only mode (paper trading)")

    @property
    def private(self) -> DeribitPrivateREST | None:
        return self._private

    def has_private_access(self) -> bool:
        return self._private is not None

    async def connect_live(self) -> None:
        self.ws = DeribitWebSocket()
        await self.ws.connect()
        await self.ws.authenticate()

    async def disconnect(self) -> None:
        if self.ws:
            await self.ws.close()
'''

with open("/root/Documents/btc-wheel-bot/deribit_client.py", "w") as f:
    f.write(deribit_client_py)
print("Written: deribit_client.py")
""")

md("### Step 18 - Test: REST connection to Deribit")
code("""import sys, importlib
sys.path.insert(0, "/root/Documents/btc-wheel-bot")
# Force fresh import
for m in ["config", "deribit_client"]:
    if m in sys.modules: del sys.modules[m]

from deribit_client import DeribitPublicREST

rest = DeribitPublicREST(timeout=15)

# Fetch BTC spot price
price_data = rest._get("get_index_price", {"index_name": "btc_usd"})
btc_price = price_data["index_price"]
print(f"BTC spot price: ${btc_price:,.0f}")
assert btc_price > 1000

# Fetch instruments (900+ expected)
instruments = rest.get_instruments("BTC")
puts = [i for i in instruments if i.option_type == "put"]
calls = [i for i in instruments if i.option_type == "call"]
print(f"Total instruments: {len(instruments)}, puts: {len(puts)}, calls: {len(calls)}")
assert len(puts) > 50

# Fetch IV history
iv_history = rest.get_historical_volatility("BTC")
print(f"IV history points: {len(iv_history)}")
assert len(iv_history) > 0

print("CHECKPOINT: Deribit REST connection OK")
""")

# PHASE 3
md("## Phase 3: Strategy Logic (Steps 19-30)")

md("""### Step 19 - Write `strategy.py`

**IV rank formula:** `(current_iv - 52w_low) / (52w_high - 52w_low)`
- Uses last 365 data points from Deribit's `get_historical_volatility`
- Returns 0.0-1.0 (0 = lowest IV in a year, 1 = highest)
- Returns 0.5 when IV has been flat (no signal either way)

**Strike scoring:** `0.7 * delta_score + 0.3 * iv_score`
- `delta_score = 1 - |actual_delta - target_mid| / target_mid`
- `iv_score = min(mark_iv / 100, 1.0)` (normalized)

**Dynamic delta (iv_dynamic_delta=True):**
- `target_mid = d_min + (d_max - d_min) * iv_rank`
- IV rank=0 (cheap IV) -> target = d_min (sell far OTM, safer)
- IV rank=1 (expensive IV) -> target = d_max (sell closer ATM, more premium)

**Wheel guard:** `_put_cycle_complete` flag prevents selling a call before the put cycle ends. Set True on ANY put expiry (OTM or ITM). Reset False after call expiry.

**Recovery call mode:** When `_last_put_was_itm=True`, only call strikes >= `_last_put_strike` are accepted. This captures BTC recovery above the assignment level.
""")
code(r"""strategy_py = '''"""
strategy.py - Core wheel strategy logic.

Responsibilities:
  - Calculate IV rank from historical volatility series
  - Select the best strike given a target delta range and cycle (put/call)
  - Decide whether to open a new position based on IV rank threshold
  - Determine the next cycle direction (put -> call -> put ...)
"""

from __future__ import annotations
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Literal

import numpy as np
from loguru import logger

from config import cfg
from deribit_client import DeribitPublicREST, Instrument, Ticker

Cycle = Literal["put", "call"]


@dataclass
class StrikeCandidate:
    instrument: Instrument
    ticker: Ticker
    score: float          # higher = preferred


@dataclass
class OpenSignal:
    """Returned when strategy decides to open a position."""
    instrument_name: str
    strike: float
    option_type: str
    expiry_ts: int
    dte: int
    delta: float
    mark_iv: float
    mark_price: float
    underlying_price: float
    cycle: Cycle
    iv_rank: float


class WheelStrategy:
    """
    BTC options wheel premium-collection strategy.

    Flow:
        1. calculate_iv_rank()  - is now a good time to sell?
        2. decide_cycle()       - sell put or call?
        3. select_strike()      - which strike to target?
        4. generate_signal()    - combine all into an OpenSignal (or None)
    """

    def __init__(self, rest_client: DeribitPublicREST) -> None:
        self._rest = rest_client
        self._current_cycle: Cycle = cfg.strategy.initial_cycle
        # Wheel guard: False until put expires, then True until call expires
        self._put_cycle_complete: bool = False
        # Recovery call tracking: set when put expires ITM
        self._last_put_was_itm: bool = False
        self._last_put_strike: float = 0.0

    def calculate_iv_rank(self, iv_history: list[tuple[int, float]]) -> float:
        """
        IV rank (0-1) over 52-week window.
        Formula: (current_iv - 52w_low) / (52w_high - 52w_low)
        """
        if len(iv_history) < 2:
            logger.warning("Insufficient IV history for rank calculation")
            return 0.0
        recent = iv_history[-365:]
        values = [v for _, v in recent]
        current_iv = values[-1]
        low_52w = min(values)
        high_52w = max(values)
        if high_52w == low_52w:
            return 0.5  # Flat IV
        rank = (current_iv - low_52w) / (high_52w - low_52w)
        logger.debug(f"IV rank: {rank:.2%} (current={current_iv:.1f}, "
                     f"low={low_52w:.1f}, high={high_52w:.1f})")
        return round(float(np.clip(rank, 0.0, 1.0)), 4)

    def decide_cycle(self, last_cycle: Cycle | None = None) -> Cycle:
        """Alternate put -> call -> put. Pass last_cycle to force direction."""
        if last_cycle is None:
            last_cycle = self._current_cycle
        next_cycle: Cycle = "call" if last_cycle == "put" else "put"
        self._current_cycle = next_cycle
        logger.debug(f"Cycle decision: {last_cycle} -> {next_cycle}")
        return next_cycle

    def select_strike(
        self,
        instruments: list[Instrument],
        tickers: dict[str, Ticker],
        cycle: Cycle,
        underlying_price: float,
        iv_rank: float = 0.5,
        delta_target_override: float | None = None,
        recovery_min_strike: float | None = None,
    ) -> StrikeCandidate | None:
        """
        Select best-scoring option strike within the target delta range.

        Filters applied in order:
          1. option_type == cycle
          2. DTE in [min_dte, max_dte]
          3. Has a live ticker with mark_price > 0
          4. delta_abs in [target_delta_min, target_delta_max]
          5. bid > 0 (liquidity check)
          6. strike >= recovery_min_strike (recovery mode only)

        Scoring: 0.7 * delta_score + 0.3 * iv_score

        Dynamic delta (iv_dynamic_delta=True):
          target_mid = d_min + (d_max - d_min) * iv_rank
          IV rank=0 -> target=d_min (far OTM)
          IV rank=1 -> target=d_max (closer ATM, more premium)
        """
        d_min = cfg.strategy.target_delta_min
        d_max = cfg.strategy.target_delta_max

        if delta_target_override is not None:
            target_delta_mid = float(np.clip(delta_target_override, d_min, d_max))
        elif cfg.strategy.iv_dynamic_delta:
            target_delta_mid = d_min + (d_max - d_min) * float(np.clip(iv_rank, 0.0, 1.0))
        else:
            target_delta_mid = (d_min + d_max) / 2.0

        candidates: list[StrikeCandidate] = []

        for inst in instruments:
            if inst.option_type != cycle:
                continue
            if not (cfg.strategy.min_dte <= inst.dte <= cfg.strategy.max_dte):
                continue
            ticker = tickers.get(inst.instrument_name)
            if ticker is None or ticker.mark_price <= 0:
                continue
            delta_abs = abs(ticker.delta)
            if not (d_min <= delta_abs <= d_max):
                continue
            if ticker.bid <= 0:
                continue
            if recovery_min_strike is not None and cycle == "call":
                if inst.strike < recovery_min_strike:
                    continue

            delta_score = 1.0 - abs(delta_abs - target_delta_mid) / target_delta_mid
            iv_score = min(ticker.mark_iv / 100.0, 1.0)
            score = 0.7 * delta_score + 0.3 * iv_score
            candidates.append(StrikeCandidate(instrument=inst, ticker=ticker, score=score))

        if not candidates:
            logger.warning(
                f"No qualifying {cycle} strikes found "
                f"(delta {d_min}-{d_max}, DTE {cfg.strategy.min_dte}-{cfg.strategy.max_dte})"
            )
            return None

        candidates.sort(key=lambda c: c.score, reverse=True)
        best = candidates[0]
        logger.info(
            f"Selected: {best.instrument.instrument_name} "
            f"delta={best.ticker.delta:.3f} IV={best.ticker.mark_iv:.1f}% "
            f"mark={best.ticker.mark_price:.4f} BTC score={best.score:.3f}"
        )
        return best

    def select_ladder_strikes(
        self,
        instruments: list[Instrument],
        tickers: dict[str, Ticker],
        underlying_price: float,
        n_legs: int,
        iv_rank: float = 0.5,
    ) -> list[StrikeCandidate]:
        """
        Select N put candidates at evenly-spaced delta targets.

        Targets at position (k+1)/(n+1) within [d_min, d_max].
        For n=2, d=[0.19, 0.41]:
          Leg 1 target: d_min + (d_max-d_min)*1/3 = ~0.26 (conservative)
          Leg 2 target: d_min + (d_max-d_min)*2/3 = ~0.33 (aggressive)

        Duplicate strikes excluded so each leg is at a distinct price level.
        """
        d_min = cfg.strategy.target_delta_min
        d_max = cfg.strategy.target_delta_max
        targets = [d_min + (d_max - d_min) * (k + 1) / (n_legs + 1) for k in range(n_legs)]
        results: list[StrikeCandidate] = []
        used_strikes: set[float] = set()

        for target in targets:
            candidate = self.select_strike(
                instruments=instruments, tickers=tickers, cycle="put",
                underlying_price=underlying_price, iv_rank=iv_rank,
                delta_target_override=target,
            )
            if candidate is None:
                continue
            if candidate.instrument.strike in used_strikes:
                continue
            used_strikes.add(candidate.instrument.strike)
            results.append(candidate)
            logger.info(
                f"Ladder leg {len(results)}/{n_legs}: "
                f"{candidate.instrument.instrument_name} "
                f"target={target:.3f} actual={candidate.ticker.delta:.3f}"
            )
        return results

    def generate_signal(
        self,
        iv_history: list[tuple[int, float]],
        instruments: list[Instrument],
        tickers: dict[str, Ticker],
        underlying_price: float,
        last_cycle: Cycle | None = None,
    ) -> OpenSignal | None:
        """
        Full strategy pass: IV rank check -> cycle -> strike -> signal.
        Returns OpenSignal if conditions are met, None otherwise.
        """
        # Step 1: IV rank filter
        iv_rank = self.calculate_iv_rank(iv_history)
        if iv_rank < cfg.strategy.iv_rank_threshold:
            logger.info(
                f"IV rank {iv_rank:.2%} below threshold "
                f"{cfg.strategy.iv_rank_threshold:.2%} - skipping"
            )
            return None

        # Step 2: Cycle decision
        cycle = self.decide_cycle(last_cycle)

        # Wheel guard: only sell call after put leg is complete
        if cycle == "call" and not self._put_cycle_complete:
            logger.info("Wheel guard: put leg not complete - staying in put mode")
            cycle = "put"
            self._current_cycle = "put"

        # Recovery call mode: require call strike >= put strike (ITM put case)
        recovery_min_strike: float | None = None
        if cycle == "call" and self._last_put_was_itm and self._last_put_strike > 0:
            recovery_min_strike = self._last_put_strike
            logger.info(f"Recovery call mode: strikes >= ${recovery_min_strike:,.0f}")

        # Step 3: Strike selection
        candidate = self.select_strike(
            instruments, tickers, cycle, underlying_price,
            iv_rank=iv_rank, recovery_min_strike=recovery_min_strike,
        )
        if candidate is None:
            return None

        return OpenSignal(
            instrument_name=candidate.instrument.instrument_name,
            strike=candidate.instrument.strike,
            option_type=cycle,
            expiry_ts=candidate.instrument.expiry_ts,
            dte=candidate.instrument.dte,
            delta=candidate.ticker.delta,
            mark_iv=candidate.ticker.mark_iv,
            mark_price=candidate.ticker.mark_price,
            underlying_price=underlying_price,
            cycle=cycle,
            iv_rank=iv_rank,
        )
'''

with open("/root/Documents/btc-wheel-bot/strategy.py", "w") as f:
    f.write(strategy_py)
print("Written: strategy.py")
""")

md("### Step 20 - Test: IV rank and strategy signal")
code("""import time
for m in ["config", "deribit_client", "strategy"]:
    if m in sys.modules: del sys.modules[m]

from deribit_client import DeribitPublicREST
from strategy import WheelStrategy

rest = DeribitPublicREST(timeout=15)
strat = WheelStrategy(rest)

iv_history = rest.get_historical_volatility("BTC")
iv_rank = strat.calculate_iv_rank(iv_history)
print(f"IV history: {len(iv_history)} points")
print(f"Current IV rank: {iv_rank:.2%}")
assert 0.0 <= iv_rank <= 1.0

# Fetch a small set of tickers to test strike selection
instruments = rest.get_instruments("BTC")
candidates = [i for i in instruments if 5 <= i.dte <= 35][:25]
tickers = {}
for inst in candidates[:15]:
    t = rest.get_ticker(inst.instrument_name)
    if t:
        tickers[inst.instrument_name] = t
    time.sleep(0.1)

underlying = next(iter(tickers.values())).underlying_price if tickers else 85000.0
signal = strat.generate_signal(iv_history, instruments, tickers, underlying)
if signal:
    print(f"Signal: {signal.instrument_name}")
    print(f"  delta={signal.delta:.3f}, IV rank={signal.iv_rank:.2%}")
else:
    print(f"No signal (IV rank {iv_rank:.2%} vs threshold {strat._current_cycle})")

print("Phase 3 CHECKPOINT PASSED")
""")

# PHASE 4
md("## Phase 4: Risk Manager (Steps 21-28)")

md("""### Step 21 - Write `risk_manager.py`

All checks return True (safe to proceed) or False (halt/block).

**Pre-trade checks** (run before every new position):
1. `check_kill_switch()` - KILL_SWITCH file exists -> halt
2. `check_max_legs()` - at max open legs -> skip
3. `check_position_size()` - can we size at least 0.1 contracts?
4. `check_collateral()` - total collateral within buffer limit
5. `check_free_margin()` - at least `min_free_equity_fraction` stays free

**In-trade checks** (run each 60-second tick):
6. `should_roll()` - delta breach OR loss breach -> roll/close
7. `check_drawdown()` - daily drawdown circuit breaker

**Sizing formula:**
- `max_notional = equity_usd * max_equity_per_leg`
- `contracts = floor(max_notional / strike / 0.1) * 0.1`  (nearest 0.1 lot)
- Minimum: 0.1 contracts (Deribit minimum lot size)

**Deribit margin formula** (for reference, same used by backtester/optimizer):
- `margin = max(0.15 - OTM_pct, 0.10) * spot * contracts * 0.1`
- OTM_pct = (spot - strike) / spot for puts (0 if ITM)
""")
code(r"""risk_manager_py = '''"""
risk_manager.py - Position sizing and risk controls.
All checks return True = safe to proceed, False = halt/roll.
"""

from __future__ import annotations
import math
import os
from dataclasses import dataclass
from pathlib import Path
from loguru import logger
from config import cfg


@dataclass
class Position:
    instrument_name: str
    strike: float
    option_type: str           # "put" | "call"
    entry_price: float         # premium received (BTC per contract)
    underlying_at_entry: float # spot price when sold
    contracts: float           # number of contracts
    current_delta: float       # current absolute delta
    current_price: float       # current mark price (BTC)
    entry_equity: float        # account equity at time of entry
    expiry_ts: int = 0         # Deribit expiry timestamp (ms)
    iv_rank_at_entry: float = 0.0
    dte_at_entry: int = 0


class RiskManager:
    """
    Enforces all risk rules before and during position lifecycle.

    Pre-trade: check_kill_switch, check_max_legs, check_position_size,
               check_collateral, check_free_margin
    In-trade:  should_roll, check_drawdown
    """

    def __init__(self) -> None:
        self._kill_switch_path = Path(cfg.risk.kill_switch_file)

    def check_kill_switch(self) -> bool:
        """Return False (block trading) if KILL_SWITCH file exists."""
        if self._kill_switch_path.exists():
            logger.critical(
                f"KILL SWITCH ACTIVE: '{cfg.risk.kill_switch_file}' found. "
                "Delete the file to resume trading."
            )
            return False
        return True

    def check_max_legs(self, open_positions: list[Position]) -> bool:
        """Block new positions if at maximum open legs."""
        if len(open_positions) >= cfg.sizing.max_open_legs:
            logger.info(f"Max open legs reached ({cfg.sizing.max_open_legs}). Skipping.")
            return False
        return True

    def calculate_contracts(self, equity_usd: float, strike_usd: float,
                             equity_fraction: float | None = None) -> float:
        """
        Calculate contracts to sell given equity and strike.

        Deribit: 1 contract = 1 BTC notional, min lot = 0.1 BTC.
        Collateral per contract = strike_usd (full notional).

        equity_fraction: override max_equity_per_leg (used by ladder).
        Returns contracts floored to nearest 0.1 lot.
        """
        if strike_usd <= 0 or equity_usd <= 0:
            return 0.0
        fraction = equity_fraction if equity_fraction is not None else cfg.sizing.max_equity_per_leg
        max_notional = equity_usd * fraction
        raw_contracts = max_notional / strike_usd
        min_lot = cfg.sizing.contract_size_btc  # 0.1
        contracts = max(min_lot, math.floor(raw_contracts / min_lot) * min_lot)
        logger.debug(f"Sizing: equity=${equity_usd:,.0f} strike=${strike_usd:,.0f} "
                     f"max_notional=${max_notional:,.0f} -> {contracts} contracts")
        return contracts

    def check_position_size(self, equity_usd: float, strike_usd: float) -> bool:
        """Return True if at least 0.1 contracts can be sized."""
        if strike_usd <= 0 or equity_usd <= 0:
            return False
        raw = (equity_usd * cfg.sizing.max_equity_per_leg) / strike_usd
        if raw < 0.1:
            logger.warning(f"Position too small: {raw:.4f} contracts at ${strike_usd:,.0f}")
            return False
        return True

    def check_collateral(self, open_positions: list[Position],
                          equity_usd: float, btc_price: float) -> bool:
        """
        Verify total collateral <= equity * collateral_buffer.
        collateral = sum(strike * contracts * contract_size_btc) for each position.
        """
        if not open_positions:
            return True
        total = sum(p.strike * p.contracts * cfg.sizing.contract_size_btc for p in open_positions)
        max_allowed = equity_usd * cfg.sizing.collateral_buffer
        if total > max_allowed:
            logger.warning(f"Collateral FAILED: ${total:,.0f} > ${max_allowed:,.0f}")
            return False
        return True

    def check_free_margin(self, equity_usd: float, open_positions: list[Position],
                           proposed_strike_usd: float, proposed_contracts: float) -> bool:
        """
        Verify opening this leg leaves >= min_free_equity_fraction of equity free.

        free_after = equity - reserved_now - reserved_new
        required   = equity * min_free_equity_fraction
        """
        threshold = cfg.sizing.min_free_equity_fraction
        if threshold <= 0.0:
            return True
        reserved_now = sum(p.strike * p.contracts * cfg.sizing.contract_size_btc
                           for p in open_positions)
        reserved_new = proposed_strike_usd * proposed_contracts * cfg.sizing.contract_size_btc
        free_after = equity_usd - reserved_now - reserved_new
        required = equity_usd * threshold
        if free_after < required:
            logger.warning(
                f"Free-margin FAILED: ${free_after:,.0f} free < ${required:,.0f} required "
                f"({threshold:.0%} of ${equity_usd:,.0f})"
            )
            return False
        return True

    def should_roll(self, position: Position) -> tuple[bool, str]:
        """
        Check if position should be rolled/closed.
        Returns (should_roll: bool, reason: str).
        Reasons: "delta_breach", "loss_breach", "ok"
        """
        if abs(position.current_delta) > cfg.risk.max_adverse_delta:
            logger.warning(
                f"Delta breach on {position.instrument_name}: "
                f"|delta|={abs(position.current_delta):.3f} > {cfg.risk.max_adverse_delta}"
            )
            return True, "delta_breach"

        pnl_btc = (position.entry_price - position.current_price) * position.contracts
        pnl_usd = pnl_btc * position.underlying_at_entry
        loss_pct = -pnl_usd / position.entry_equity

        if loss_pct > cfg.risk.max_loss_per_leg:
            logger.warning(
                f"Loss breach on {position.instrument_name}: "
                f"loss={loss_pct:.2%} > {cfg.risk.max_loss_per_leg:.2%}"
            )
            return True, "loss_breach"

        return False, "ok"

    def check_drawdown(self, equity_curve: list[float]) -> bool:
        """Halt trading if drawdown from peak exceeds max_daily_drawdown."""
        if len(equity_curve) < 2:
            return True
        peak = max(equity_curve)
        current = equity_curve[-1]
        drawdown = (peak - current) / peak
        if drawdown > cfg.risk.max_daily_drawdown:
            logger.error(f"Drawdown limit: {drawdown:.2%} > {cfg.risk.max_daily_drawdown:.2%}")
            return False
        return True

    def full_pre_trade_check(self, open_positions: list[Position], equity_usd: float,
                              strike_usd: float, btc_price: float,
                              proposed_contracts: float | None = None) -> bool:
        """Run all 5 pre-trade checks. Returns True only if all pass."""
        if proposed_contracts is None:
            proposed_contracts = self.calculate_contracts(equity_usd, strike_usd)
        checks = [
            self.check_kill_switch(),
            self.check_max_legs(open_positions),
            self.check_position_size(equity_usd, strike_usd),
            self.check_collateral(open_positions, equity_usd, btc_price),
            self.check_free_margin(equity_usd, open_positions, strike_usd, proposed_contracts),
        ]
        result = all(checks)
        if result:
            logger.info("Pre-trade checks PASSED")
        else:
            logger.warning("Pre-trade checks FAILED - position not opened")
        return result
'''

with open("/root/Documents/btc-wheel-bot/risk_manager.py", "w") as f:
    f.write(risk_manager_py)
print("Written: risk_manager.py")
""")

md("### Step 22 - Test: risk manager checks")
code("""for m in ["config", "risk_manager"]:
    if m in sys.modules: del sys.modules[m]

from risk_manager import RiskManager, Position

rm = RiskManager()
equity = 50_000.0
strike = 80_000.0
btc = 85_000.0

# Test contract sizing
contracts = rm.calculate_contracts(equity, strike)
print(f"Contracts for $50k equity, $80k strike: {contracts}")
assert contracts >= 0.1

# Test pre-trade with no positions
ok = rm.full_pre_trade_check([], equity, strike, btc)
print(f"Pre-trade check (no positions): {'PASS' if ok else 'FAIL'}")
assert ok

# Test drawdown check
assert rm.check_drawdown([50000, 49000, 48000]) == True   # 4% DD, under 10% limit
assert rm.check_drawdown([50000, 40000]) == False          # 20% DD, over 10% limit

# Test delta breach
pos = Position("BTC-XYZ-P", 80000, "put", 0.01, 85000, 1.0, 0.5, 0.03, 50000)
should_roll, reason = rm.should_roll(pos)
print(f"Delta breach (delta=0.5 > 0.4): roll={should_roll}, reason={reason}")
assert should_roll and reason == "delta_breach"

print("Phase 4 CHECKPOINT PASSED")
""")

# PHASE 5 overview
md("## Phase 5: Bot Core (Steps 29-45)")

md("""### Step 23 - Bot architecture overview

`WheelBot` is an async class running a 60-second tick loop.

**Modes:**
- `paper=True`: Live market data, simulated orders, paper P&L tracking
- `paper=False`: Live market data, real WebSocket orders (testnet or mainnet)

**State files written each tick:**
- `data/bot_state.json` - running status, mode, heartbeat
- `data/current_position.json` - open position for mobile API
- `data/tick_log.csv` - one row per tick for charting
- `bot_heartbeat.json` - PID, timestamp, equity snapshot

**Key flags on WheelStrategy:**
- `_put_cycle_complete` - False until put expires, True until call expires
- `_last_put_was_itm` - True if last put expired ITM (triggers recovery call mode)
- `_last_put_strike` - put strike for recovery call minimum

**Regime price tracking:**
- `_regime_daily_prices` deque: one price per UTC calendar day
- Used to compute N-day SMA for regime filter
- Fails open during warmup (< N days)

**Paper mode expiry detection:**
- `_parse_expiry()`: parses `BTC-25APR25-90000-P` -> datetime
- At 08:00 UTC: compare underlying_price vs strike -> ITM/OTM
- Sets `_put_cycle_complete` and `_last_put_was_itm` flags
""")

md("### Step 24 - Write `notifier.py` (Telegram alerts)")
code(r"""notifier_py = '''"""
notifier.py - Telegram notification helper for BTC Wheel Bot.
"""

from __future__ import annotations
import json
import os
from pathlib import Path

_MASTER_CONFIG_PATH = Path(__file__).parent / "data" / "notifier_config.json"


def _load() -> dict:
    """
    Load notifier config. Farm bots set WHEEL_BOT_DATA_DIR to their data dir.
    Try {DATA_DIR}/notifier_config.json first, then fall back to the master
    data/notifier_config.json so farm bots share the same Telegram credentials.
    """
    data_dir = os.environ.get("WHEEL_BOT_DATA_DIR", "")
    if data_dir:
        bot_cfg = Path(data_dir) / "notifier_config.json"
        if bot_cfg.exists():
            try:
                return json.loads(bot_cfg.read_text())
            except Exception:
                pass
    try:
        return json.loads(_MASTER_CONFIG_PATH.read_text())
    except Exception:
        return {}


def _send(text: str) -> None:
    cfg = _load()
    token = cfg.get("bot_token", "")
    chat_id = cfg.get("chat_id", "")
    if not token or not chat_id:
        return
    try:
        import requests
        requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat_id, "text": text, "parse_mode": "HTML"},
            timeout=5,
        )
    except Exception:
        pass


def notify_bot_started(mode: str) -> None:
    _send(f"Bot started - mode: <code>{mode}</code>")


def notify_bot_stopped() -> None:
    _send("Bot stopped")


def notify_trade_opened(instrument: str, strike: float,
                         premium_btc: float, dte: int) -> None:
    _send(
        f"Opened {instrument}\n"
        f"Strike: ${strike:,.0f}  Premium: {premium_btc:.5f} BTC  DTE: {dte}"
    )


def notify_trade_closed(instrument: str, pnl_usd: float, reason: str) -> None:
    sign = "+" if pnl_usd >= 0 else ""
    _send(f"Closed {instrument}\nP&L: {sign}${pnl_usd:,.2f}  Reason: {reason}")


def notify_error(message: str) -> None:
    _send(f"Bot error\n{message[:300]}")
'''

with open("/root/Documents/btc-wheel-bot/notifier.py", "w") as f:
    f.write(notifier_py)
print("Written: notifier.py")
""")

md("### Step 25 - Write `hedge_manager.py`")
code(r"""hedge_manager_py = '''"""
hedge_manager.py - Delta-neutral hedging via BTC-PERPETUAL futures.

Sign convention:
  Short put  -> portfolio delta POSITIVE (+delta * contracts)
                Hedge: SHORT perp (negative position)
  Short call -> portfolio delta NEGATIVE (-delta * contracts)
                Hedge: LONG perp (positive position)
  Net delta = option_delta + perp_position ~= 0

Rebalance fires when |required_perp - current_perp| >= rebalance_threshold.
"""

from __future__ import annotations
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any
from loguru import logger

PERP_MIN_LOT = 0.1  # Deribit BTC-PERPETUAL minimum lot size


@dataclass
class HedgeState:
    perp_position_btc: float = 0.0
    avg_entry_price: float = 0.0
    realised_pnl_usd: float = 0.0
    funding_paid_usd: float = 0.0
    rebalance_count: int = 0


class HedgeManager:
    """
    Tracks and rebalances a BTC-PERPETUAL position to neutralise option delta.

    Usage from bot.py tick loop:
        await self._hedge.rebalance(pos.option_type, pos.current_delta,
                                    pos.contracts, spot_price, ws_client)
        # On position close:
        await self._hedge.close_all(spot_price, ws_client)
    """

    def __init__(self, paper: bool = True, rebalance_threshold: float = 0.05,
                 state_path: Path | None = None) -> None:
        self._paper = paper
        self._rebalance_threshold = rebalance_threshold
        self._state_path = state_path or (Path(__file__).parent / "data" / "hedge_state.json")
        self._state = self._load_state()

    def _load_state(self) -> HedgeState:
        try:
            if self._state_path.exists():
                data = json.loads(self._state_path.read_text())
                return HedgeState(**{k: v for k, v in data.items()
                                     if k in HedgeState.__dataclass_fields__})
        except Exception:
            pass
        return HedgeState()

    def _save_state(self) -> None:
        try:
            self._state_path.parent.mkdir(exist_ok=True)
            self._state_path.write_text(json.dumps(asdict(self._state), indent=2))
        except Exception:
            pass

    def required_hedge_btc(self, option_type: str, delta_abs: float, contracts: float) -> float:
        """Ideal perp position to make net delta zero."""
        size = delta_abs * contracts
        return -size if option_type == "put" else +size

    def net_delta_btc(self, option_type: str, delta_abs: float, contracts: float) -> float:
        """Current net portfolio delta (options + perp). 0 = perfectly hedged."""
        option_delta = +delta_abs * contracts if option_type == "put" else -delta_abs * contracts
        return option_delta + self._state.perp_position_btc

    def unrealised_pnl_usd(self, current_spot: float) -> float:
        pos = self._state.perp_position_btc
        entry = self._state.avg_entry_price
        if pos == 0.0 or entry == 0.0 or current_spot == 0.0:
            return 0.0
        return pos * (current_spot - entry)

    async def rebalance(self, option_type: str, delta_abs: float, contracts: float,
                         spot_price: float, ws_client: Any = None) -> float:
        """Check if hedge needs adjustment and execute. Returns BTC adjustment made."""
        required = self.required_hedge_btc(option_type, delta_abs, contracts)
        raw_adjustment = required - self._state.perp_position_btc
        lots = round(raw_adjustment / PERP_MIN_LOT)
        adjustment = lots * PERP_MIN_LOT
        if abs(adjustment) < self._rebalance_threshold:
            return 0.0
        if self._paper:
            await self._paper_trade(adjustment, spot_price)
        else:
            await self._live_trade(adjustment, spot_price, ws_client)
        return adjustment

    async def close_all(self, spot_price: float, ws_client: Any = None) -> float:
        """Close entire hedge position. Returns realised P&L from closing."""
        if abs(self._state.perp_position_btc) < PERP_MIN_LOT / 2:
            self._state.perp_position_btc = 0.0
            self._state.avg_entry_price = 0.0
            self._save_state()
            return 0.0
        closing_trade = -self._state.perp_position_btc
        if self._paper:
            return await self._paper_trade(closing_trade, spot_price)
        else:
            return await self._live_trade(closing_trade, spot_price, ws_client)

    async def _paper_trade(self, adjustment_btc: float, spot_price: float) -> float:
        """Simulate BTC-PERPETUAL trade. Returns realised P&L."""
        old_pos = self._state.perp_position_btc
        old_entry = self._state.avg_entry_price
        realised = 0.0
        # Realise P&L on any portion being closed
        if (old_pos != 0.0 and old_entry > 0.0
                and ((old_pos > 0 and adjustment_btc < 0)
                     or (old_pos < 0 and adjustment_btc > 0))):
            closing_btc = min(abs(adjustment_btc), abs(old_pos))
            realised = closing_btc * (spot_price - old_entry) if old_pos > 0 else \
                       closing_btc * (old_entry - spot_price)
            self._state.realised_pnl_usd += realised
        new_pos = round(old_pos + adjustment_btc, 4)
        # Update weighted average entry
        if abs(new_pos) < 0.001:
            self._state.avg_entry_price = 0.0
        elif old_pos == 0.0 or (old_pos > 0) != (new_pos > 0):
            self._state.avg_entry_price = spot_price
        elif (adjustment_btc > 0 and new_pos > 0) or (adjustment_btc < 0 and new_pos < 0):
            self._state.avg_entry_price = (
                abs(old_pos) * old_entry + abs(adjustment_btc) * spot_price) / abs(new_pos)
        self._state.perp_position_btc = new_pos
        self._state.rebalance_count += 1
        direction = "BUY" if adjustment_btc > 0 else "SELL"
        logger.info(f"[PAPER HEDGE] {direction} {abs(adjustment_btc):.3f} BTC-PERP @ "
                    f"${spot_price:,.0f} | position: {new_pos:+.3f} BTC"
                    + (f" | realised: ${realised:+.2f}" if realised else ""))
        self._save_state()
        return realised

    async def _live_trade(self, adjustment_btc: float, spot_price: float,
                           ws_client: Any) -> float:
        """Place real BTC-PERPETUAL market order via WebSocket."""
        if ws_client is None:
            logger.error("HedgeManager: ws_client required for live trading")
            return 0.0
        direction = "buy" if adjustment_btc > 0 else "sell"
        try:
            method = "private/buy" if direction == "buy" else "private/sell"
            result = await ws_client._rpc(method, {
                "instrument_name": "BTC-PERPETUAL",
                "amount": abs(adjustment_btc),
                "type": "market",
                "label": "wheel_hedge",
            })
            fill_price = float(result.get("order", {}).get("average_price", spot_price))
            logger.info(f"[LIVE HEDGE] {direction.upper()} {abs(adjustment_btc):.3f} BTC-PERP @ "
                        f"${fill_price:,.0f}")
            return await self._paper_trade(adjustment_btc, fill_price)
        except Exception as exc:
            logger.error(f"HedgeManager live trade failed: {exc}")
            return 0.0

    @property
    def position_btc(self) -> float:
        return self._state.perp_position_btc

    @property
    def realised_pnl_usd(self) -> float:
        return self._state.realised_pnl_usd

    @property
    def rebalance_count(self) -> int:
        return self._state.rebalance_count

    def reset(self) -> None:
        self._state = HedgeState()
        self._save_state()
        logger.info("HedgeManager: state reset")

    def to_dict(self, spot_price: float = 0.0) -> dict:
        return {
            "perp_position_btc": round(self._state.perp_position_btc, 4),
            "avg_entry_price": round(self._state.avg_entry_price, 2),
            "unrealised_pnl_usd": round(self.unrealised_pnl_usd(spot_price), 2),
            "realised_pnl_usd": round(self._state.realised_pnl_usd, 2),
            "funding_paid_usd": round(self._state.funding_paid_usd, 2),
            "rebalance_count": self._state.rebalance_count,
        }
'''

with open("/root/Documents/btc-wheel-bot/hedge_manager.py", "w") as f:
    f.write(hedge_manager_py)
print("Written: hedge_manager.py")
""")

# Write notebook up to here
nb.cells = cells
path = "/sessions/keen-eloquent-cray/mnt/Documents/btc-wheel-bot/btc_wheel_bot_reconstruction_guide.ipynb"
with open(path, "w") as f:
    nbformat.write(nb, f)

print(f"Notebook written: {len(cells)} cells")
