"""Build the BTC Wheel Bot reconstruction guide notebook."""
import nbformat
from nbformat.v4 import new_notebook, new_markdown_cell, new_code_cell

nb = new_notebook()
cells = []

def md(source): cells.append(new_markdown_cell(source))
def code(source): cells.append(new_code_cell(source))

# ─────────────────────────────────────────────────────────────────────────────
# TITLE
# ─────────────────────────────────────────────────────────────────────────────
md("""# BTC Wheel Bot — Complete Reconstruction Guide

**13 Phases · ~230 Steps**

This notebook contains everything needed to rebuild the BTC Wheel Bot from scratch.
Run cells top-to-bottom in a fresh directory.  Each step does exactly one thing and
includes verification.

> **Architecture summary:**  Sell BTC put options (collecting premium), alternate to
> covered calls after expiry, managed by a 60-second async loop.  Delta-hedged via
> BTC-PERPETUAL perp.  Parameters evolved by a genetic algorithm.  Mobile PWA served
> over Cloudflare Tunnel.

---
## Quick-reference

| Module | Role |
|--------|------|
| `config.py` / `config.yaml` | All configuration, typed dataclasses |
| `deribit_client.py` | Deribit REST + WebSocket wrapper |
| `strategy.py` | IV rank, strike selection, wheel cycle |
| `risk_manager.py` | Position sizing, kill-switch, drawdown |
| `bot.py` | 60-second async main loop |
| `main.py` | CLI entry point (backtest/paper/testnet/live) |
| `backtester.py` | Black-Scholes historical simulation |
| `optimizer.py` | Genetic algorithm over all parameters |
| `config_store.py` | Named config CRUD + lifecycle |
| `bot_farm.py` | Supervisor process for parallel paper bots |
| `readiness_validator.py` | 8-check go/no-go for live promotion |
| `api.py` | FastAPI backend (mobile app talks here) |
| `notifier.py` | Telegram alerts |
| `hedge_manager.py` | Delta-neutral BTC-PERP hedge |
| `ai_overseer.py` | LLM safety layer (halt-only) |
""")

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 0: Prerequisites
# ─────────────────────────────────────────────────────────────────────────────
md("## Phase 0: Prerequisites & Project Setup (Steps 1–12)")

md("### Step 1 — Create project directory structure\n\nAll bot files live in a single flat directory.  Subdirectories: `data/`, `logs/`, `configs/`, `farm/`, `mobile-app/`.")
code("""import os, pathlib

PROJECT = pathlib.Path.home() / "Documents" / "btc-wheel-bot"
for d in ["data", "data/optimizer", "logs", "configs", "farm", "mobile-app/src/components"]:
    (PROJECT / d).mkdir(parents=True, exist_ok=True)

print("Created:", PROJECT)
print("Subdirs:", [d.name for d in PROJECT.iterdir() if d.is_dir()])
""")

md("### Step 2 — Check Python version (needs 3.10+)\n\nThe bot uses `match` statements, `X | Y` type unions, and `asyncio.run()`.")
code("""import sys
v = sys.version_info
print(f"Python {v.major}.{v.minor}.{v.micro}")
assert v >= (3, 10), f"Need Python 3.10+, got {v.major}.{v.minor}"
print("OK")
""")

md("### Step 3 — Install Python dependencies\n\nFull pip install list from `requirements.txt`.")
code("""!pip install -q \\
    aiohttp>=3.9.0 \\
    websockets>=12.0 \\
    requests>=2.31.0 \\
    pandas>=2.0.0 numpy>=1.26.0 scipy>=1.12.0 \\
    matplotlib>=3.8.0 \\
    pyyaml>=6.0.1 python-dotenv>=1.0.0 \\
    loguru>=0.7.2 \\
    tabulate>=0.9.0 \\
    fastapi>=0.111.0 "uvicorn[standard]>=0.30.0" \\
    httpx websockets pydantic
print("Dependencies installed")
""")

md("### Step 4 — Node.js check (for mobile-app build)\n\nNeeds Node 20+.")
code("""import subprocess
r = subprocess.run(["node", "--version"], capture_output=True, text=True)
print("node:", r.stdout.strip() or "NOT FOUND")
r2 = subprocess.run(["npm", "--version"], capture_output=True, text=True)
print("npm:", r2.stdout.strip() or "NOT FOUND")
""")

md("### Step 5 — Create `.env` file template\n\nSecrets come ONLY from environment variables, never from `config.yaml`.\n\n- `DERIBIT_API_KEY` / `DERIBIT_API_SECRET` — from https://www.deribit.com/account/api\n- `DERIBIT_TESTNET` — `true` for test.deribit.com, `false` for mainnet\n- `WHEEL_API_KEY` — auto-generated by `api.py` on first run\n- `LOG_LEVEL` — DEBUG | INFO | WARNING | ERROR")
code("""%%writefile /root/Documents/btc-wheel-bot/.env.example
# ── Deribit Credentials ──────────────────────────────────────────────────────
# Get these from: https://www.deribit.com/account/api
# Never commit real credentials to version control.
DERIBIT_API_KEY=your_api_key_here
DERIBIT_API_SECRET=your_api_secret_here

# Use testnet for development (overrides config.yaml deribit.testnet)
DERIBIT_TESTNET=true

# ── Mobile API ───────────────────────────────────────────────────────────────
# Auto-generated by api.py on first run — copy from .env after generation
WHEEL_API_KEY=

# ── Optional Overrides ───────────────────────────────────────────────────────
LOG_LEVEL=INFO       # DEBUG | INFO | WARNING | ERROR
""")

md("### Step 6–8 — Create runtime directories and verify imports")
code("""import os
os.makedirs("data/optimizer", exist_ok=True)
os.makedirs("logs", exist_ok=True)
os.makedirs("configs", exist_ok=True)
os.makedirs("farm", exist_ok=True)
print("Runtime dirs ready")
""")

code("""# Verify all Python stdlib + third-party imports work
import asyncio, json, csv, time, math, random, copy, signal
import subprocess, multiprocessing, argparse
import aiohttp, requests, websockets
import pandas as pd, numpy as np
from scipy.stats import norm
import matplotlib, yaml
from dotenv import load_dotenv
from loguru import logger
from fastapi import FastAPI
print("All imports OK")
""")

md("### Step 9 — Create `.gitignore`")
code("""%%writefile /root/Documents/btc-wheel-bot/.gitignore
.env
__pycache__/
*.pyc
*.pyo
*.egg-info/
.venv/
venv/
*.log
data/*.csv
data/*.json
data/optimizer/
KILL_SWITCH
*.bak
mobile-app/node_modules/
mobile-app/dist/
farm/
*.png
""")

md("### Step 10–11 — Initialize git and GitHub (manual step)\n\n```bash\ngit init\ngit add .\ngit commit -m 'Initial commit: BTC wheel bot skeleton'\n# Then on GitHub: create repo banksiasprings/btc-wheel-bot\ngit remote add origin git@github.com:banksiasprings/btc-wheel-bot.git\ngit push -u origin main\n```")
code("""import subprocess
r = subprocess.run(["git", "rev-parse", "--is-inside-work-tree"],
                   capture_output=True, text=True, cwd="/root/Documents/btc-wheel-bot")
print("Git repo:", "yes" if r.returncode == 0 else "no — run: git init")
""")

md("### Step 12 — CHECKPOINT: verify directory structure")
code("""import os
required = ["data", "logs", "configs", "farm", "mobile-app"]
for d in required:
    exists = os.path.isdir(f"/root/Documents/btc-wheel-bot/{d}")
    print(f"  {'✓' if exists else '✗'} {d}/")
assert all(os.path.isdir(f"/root/Documents/btc-wheel-bot/{d}") for d in required)
print("CHECKPOINT PASSED")
""")

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 1: Configuration System
# ─────────────────────────────────────────────────────────────────────────────
md("## Phase 1: Configuration System (Steps 13–25)")

md("### Step 13 — Write `config.yaml`\n\nAll non-secret configuration lives here.  The optimizer evolves these values and saves named configs in `configs/`.")
code("""%%writefile /root/Documents/btc-wheel-bot/config.yaml
backtest:
  approx_otm_offset: 0.0338
  lookback_months: 12
  premium_fraction_of_spot: 0.0289
  results_csv: data/backtest_trades.csv
  results_image: backtest_results.png
  risk_free_rate: 0.04
  starting_equity: 1000.0
  transaction_cost: 0.5
deribit:
  currency: BTC
  request_timeout: 10
  rest_url_mainnet: https://www.deribit.com/api/v2
  rest_url_testnet: https://test.deribit.com/api/v2
  testnet: true
  ws_url_mainnet: wss://www.deribit.com/ws/api/v2
  ws_url_testnet: wss://test.deribit.com/ws/api/v2
execution:
  order_confirm_timeout: 30
  poll_interval: 60
  slippage_tolerance: 0.005
hedge:
  enabled: true
  rebalance_threshold: 0.05
logging:
  level: INFO
  log_dir: logs
  retention: 30 days
  rotation: 1 day
  trade_log_csv: data/trades.csv
overseer:
  check_interval_minutes: 60
  drawdown_warning_threshold: 0.05
  enabled: true
  iv_spike_warning_threshold: 0.85
risk:
  kill_switch_file: KILL_SWITCH
  max_adverse_delta: 0.4
  max_daily_drawdown: 0.1
  max_loss_per_leg: 0.02
  roll_enabled: false
  roll_min_dte: 3
sizing:
  collateral_buffer: 1.0
  contract_size_btc: 0.1
  ladder_enabled: false
  ladder_legs: 2
  max_equity_per_leg: 0.0828
  max_open_legs: 1
  min_free_equity_fraction: 0.1007
  regime_ma_days: 50
  use_regime_filter: false
strategy:
  expiry_execution_hour: 8
  expiry_preference:
  - weekly
  - monthly
  initial_cycle: put
  iv_dynamic_delta: true
  iv_rank_threshold: 0.701
  liquidity_top_n: 100
  max_dte: 37
  min_dte: 3
  target_delta_max: 0.4057
  target_delta_min: 0.1883
""")

md("### Step 14 — Write `config.py`\n\nTyped dataclasses for all config sections.  The module-level singleton `cfg` is imported by every other module.\n\n**Key design:** secrets come ONLY from environment variables (lines with `os.getenv`), never from YAML.")
code(r"""%%writefile /root/Documents/btc-wheel-bot/config.py
"""
config.py — Centralised configuration loader for BTC Wheel Bot.

Loads settings from config.yaml, then overlays values from environment
variables (via .env or system env).  Exposes a single typed Config object
that every other module imports.

Usage:
    from config import cfg
    print(cfg.strategy.iv_rank_threshold)
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

import yaml
from dotenv import load_dotenv

# Load .env before reading environment variables
load_dotenv()

# ── Sub-configs ────────────────────────────────────────────────────────────────


@dataclass
class DeribitConfig:
    testnet: bool
    ws_url_testnet: str
    ws_url_mainnet: str
    rest_url_testnet: str
    rest_url_mainnet: str
    request_timeout: int
    currency: str
    api_key: str = ""
    api_secret: str = ""

    @property
    def ws_url(self) -> str:
        return self.ws_url_testnet if self.testnet else self.ws_url_mainnet

    @property
    def rest_url(self) -> str:
        return self.rest_url_testnet if self.testnet else self.rest_url_mainnet


@dataclass
class StrategyConfig:
    iv_rank_threshold: float
    target_delta_min: float
    target_delta_max: float
    expiry_preference: list[str]
    min_dte: int
    max_dte: int
    initial_cycle: Literal["put", "call"]
    expiry_execution_hour: int
    liquidity_top_n: int
    iv_dynamic_delta: bool = False


@dataclass
class SizingConfig:
    max_equity_per_leg: float
    max_open_legs: int
    collateral_buffer: float
    contract_size_btc: float
    min_free_equity_fraction: float = 0.25
    use_regime_filter: bool = False
    regime_ma_days: int = 50
    ladder_enabled: bool = False
    ladder_legs: int = 2


@dataclass
class RiskConfig:
    max_adverse_delta: float
    max_loss_per_leg: float
    max_daily_drawdown: float
    kill_switch_file: str
    roll_enabled: bool = False
    roll_min_dte: int = 3


@dataclass
class ExecutionConfig:
    poll_interval: int
    order_confirm_timeout: int
    slippage_tolerance: float


@dataclass
class BacktestConfig:
    starting_equity: float
    lookback_months: int
    transaction_cost: float
    approx_otm_offset: float
    premium_fraction_of_spot: float
    risk_free_rate: float
    results_image: str
    results_csv: str


@dataclass
class HedgeConfig:
    enabled: bool = True
    rebalance_threshold: float = 0.05


@dataclass
class OverseerConfig:
    enabled: bool
    check_interval_minutes: int
    drawdown_warning_threshold: float
    iv_spike_warning_threshold: float


@dataclass
class LoggingConfig:
    level: str
    rotation: str
    retention: str
    log_dir: str
    trade_log_csv: str


@dataclass
class Config:
    deribit: DeribitConfig
    strategy: StrategyConfig
    sizing: SizingConfig
    risk: RiskConfig
    execution: ExecutionConfig
    backtest: BacktestConfig
    overseer: OverseerConfig
    logging: LoggingConfig
    hedge: HedgeConfig = None  # type: ignore[assignment]

    def __post_init__(self) -> None:
        if self.hedge is None:
            self.hedge = HedgeConfig()


# ── Loader ─────────────────────────────────────────────────────────────────────


def _load_yaml(path: Path) -> dict:
    """Load and parse a YAML file."""
    if not path.exists():
        raise FileNotFoundError(f"Config file not found: {path}")
    with open(path) as fh:
        return yaml.safe_load(fh) or {}


def load_config(yaml_path: str | Path | None = None) -> Config:
    """
    Load configuration from YAML file and environment variable overrides.

    Environment variable precedence (highest wins):
        DERIBIT_API_KEY, DERIBIT_API_SECRET — auth credentials
        DERIBIT_TESTNET — "true" / "false" override
        LOG_LEVEL — logging level override
    """
    if yaml_path is None:
        config_path = os.environ.get("WHEEL_BOT_CONFIG", None)
        if config_path:
            yaml_path = Path(config_path)
        else:
            yaml_path = Path(__file__).parent / "config.yaml"

    raw = _load_yaml(Path(yaml_path))

    d = raw["deribit"]
    deribit_cfg = DeribitConfig(
        testnet=os.getenv("DERIBIT_TESTNET", str(d["testnet"])).lower() == "true",
        ws_url_testnet=d["ws_url_testnet"],
        ws_url_mainnet=d["ws_url_mainnet"],
        rest_url_testnet=d["rest_url_testnet"],
        rest_url_mainnet=d["rest_url_mainnet"],
        request_timeout=int(d["request_timeout"]),
        currency=d["currency"],
        # Secrets always come from environment — never YAML
        api_key=os.getenv("DERIBIT_API_KEY", ""),
        api_secret=os.getenv("DERIBIT_API_SECRET", ""),
    )

    s = raw["strategy"]
    strategy_cfg = StrategyConfig(
        iv_rank_threshold=float(s["iv_rank_threshold"]),
        target_delta_min=float(s["target_delta_min"]),
        target_delta_max=float(s["target_delta_max"]),
        expiry_preference=list(s["expiry_preference"]),
        min_dte=int(s["min_dte"]),
        max_dte=int(s["max_dte"]),
        initial_cycle=s["initial_cycle"],
        expiry_execution_hour=int(s["expiry_execution_hour"]),
        liquidity_top_n=int(s["liquidity_top_n"]),
        iv_dynamic_delta=bool(s.get("iv_dynamic_delta", False)),
    )

    sz = raw["sizing"]
    sizing_cfg = SizingConfig(
        max_equity_per_leg=float(sz["max_equity_per_leg"]),
        max_open_legs=int(sz["max_open_legs"]),
        collateral_buffer=float(sz["collateral_buffer"]),
        contract_size_btc=float(sz["contract_size_btc"]),
        min_free_equity_fraction=float(sz.get("min_free_equity_fraction", 0.25)),
        use_regime_filter=bool(sz.get("use_regime_filter", False)),
        regime_ma_days=int(sz.get("regime_ma_days", 50)),
        ladder_enabled=bool(sz.get("ladder_enabled", False)),
        ladder_legs=int(sz.get("ladder_legs", 2)),
    )

    r = raw["risk"]
    risk_cfg = RiskConfig(
        max_adverse_delta=float(r["max_adverse_delta"]),
        max_loss_per_leg=float(r["max_loss_per_leg"]),
        max_daily_drawdown=float(r["max_daily_drawdown"]),
        kill_switch_file=r["kill_switch_file"],
        roll_enabled=bool(r.get("roll_enabled", False)),
        roll_min_dte=int(r.get("roll_min_dte", 3)),
    )

    e = raw["execution"]
    exec_cfg = ExecutionConfig(
        poll_interval=int(e["poll_interval"]),
        order_confirm_timeout=int(e["order_confirm_timeout"]),
        slippage_tolerance=float(e["slippage_tolerance"]),
    )

    bt = raw["backtest"]
    backtest_cfg = BacktestConfig(
        starting_equity=float(bt["starting_equity"]),
        lookback_months=int(bt["lookback_months"]),
        transaction_cost=float(bt["transaction_cost"]),
        approx_otm_offset=float(bt["approx_otm_offset"]),
        premium_fraction_of_spot=float(bt["premium_fraction_of_spot"]),
        risk_free_rate=float(bt["risk_free_rate"]),
        results_image=bt["results_image"],
        results_csv=bt["results_csv"],
    )

    ov = raw.get("overseer", {})
    overseer_cfg = OverseerConfig(
        enabled=bool(ov.get("enabled", True)),
        check_interval_minutes=int(ov.get("check_interval_minutes", 60)),
        drawdown_warning_threshold=float(ov.get("drawdown_warning_threshold", 0.05)),
        iv_spike_warning_threshold=float(ov.get("iv_spike_warning_threshold", 0.85)),
    )

    lg = raw["logging"]
    logging_cfg = LoggingConfig(
        level=os.getenv("LOG_LEVEL", lg["level"]),
        rotation=lg["rotation"],
        retention=lg["retention"],
        log_dir=lg["log_dir"],
        trade_log_csv=lg["trade_log_csv"],
    )

    hg = raw.get("hedge", {})
    hedge_cfg = HedgeConfig(
        enabled=bool(hg.get("enabled", True)),
        rebalance_threshold=float(hg.get("rebalance_threshold", 0.05)),
    )

    cfg_obj = Config(
        deribit=deribit_cfg,
        strategy=strategy_cfg,
        sizing=sizing_cfg,
        risk=risk_cfg,
        execution=exec_cfg,
        backtest=backtest_cfg,
        overseer=overseer_cfg,
        logging=logging_cfg,
        hedge=hedge_cfg,
    )

    # Override data paths when running inside the bot farm
    data_dir = os.environ.get("WHEEL_BOT_DATA_DIR", None)
    if data_dir:
        if hasattr(cfg_obj.logging, "trade_log_csv"):
            cfg_obj.logging.trade_log_csv = os.path.join(
                data_dir, os.path.basename(cfg_obj.logging.trade_log_csv)
            )
        if hasattr(cfg_obj.logging, "log_dir"):
            cfg_obj.logging.log_dir = os.path.join(data_dir, "logs")
        if hasattr(cfg_obj.backtest, "results_csv"):
            cfg_obj.backtest.results_csv = os.path.join(
                data_dir, os.path.basename(cfg_obj.backtest.results_csv)
            )
        if hasattr(cfg_obj.backtest, "results_image"):
            cfg_obj.backtest.results_image = os.path.join(
                data_dir, os.path.basename(cfg_obj.backtest.results_image)
            )
        if hasattr(cfg_obj.risk, "kill_switch_file"):
            cfg_obj.risk.kill_switch_file = os.path.join(
                data_dir, os.path.basename(cfg_obj.risk.kill_switch_file)
            )

    return cfg_obj


# Module-level singleton — import this everywhere
cfg: Config = load_config()
""")

md("### Step 15 — Secret isolation principle\n\n**Rule:** `config.yaml` NEVER contains API keys, tokens, or passwords.\n\nAll secrets flow through environment variables:\n- Set in `.env` (not committed to git)\n- Or injected by the OS/LaunchAgent\n- `load_dotenv()` at top of `config.py` loads `.env` on startup\n- `os.getenv(\"DERIBIT_API_KEY\", \"\")` reads them\n\nThis means the same `config.yaml` can be committed to git safely.")

md("### Step 16 — Test: config loads correctly")
code("""import sys
sys.path.insert(0, "/root/Documents/btc-wheel-bot")
os.chdir("/root/Documents/btc-wheel-bot")

from config import cfg
print(f"iv_rank_threshold: {cfg.strategy.iv_rank_threshold}")
print(f"target_delta_min:  {cfg.strategy.target_delta_min}")
print(f"target_delta_max:  {cfg.strategy.target_delta_max}")
print(f"max_equity_per_leg:{cfg.sizing.max_equity_per_leg}")
print(f"testnet:           {cfg.deribit.testnet}")
assert cfg.strategy.iv_rank_threshold > 0
print("Config load: OK")
""")

md("### Step 17 — Config section purposes\n\n| Section | Purpose |\n|---------|--------|\n| `deribit` | URLs, currency, timeouts |\n| `strategy` | IV rank threshold, delta range, DTE range, cycle |\n| `sizing` | Equity per leg, max legs, collateral buffer, ladder |\n| `risk` | Delta breach limit, loss per leg, kill-switch path |\n| `execution` | Poll interval (60s), order timeout, slippage |\n| `backtest` | Starting equity, lookback months, transaction cost |\n| `hedge` | Enable/disable, rebalance threshold (0.05 BTC drift) |\n| `overseer` | AI check interval, warning thresholds |\n| `logging` | Level, rotation, retention |\n\nThe optimizer saves evolved values for `strategy`, `sizing`, `backtest` sections into named configs in `configs/`.")

md("### Step 18 — CHECKPOINT: config system")
code("""from config import cfg, load_config
assert cfg.strategy.iv_rank_threshold == 0.701
assert cfg.sizing.max_open_legs == 1
assert cfg.deribit.currency == "BTC"
assert cfg.hedge.enabled is True
print("Phase 1 CHECKPOINT PASSED")
""")

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 2: Deribit API Client
# ─────────────────────────────────────────────────────────────────────────────
md("## Phase 2: Deribit API Client (Steps 19–40)")

md("""### Step 19 — Deribit API structure

Deribit has two interfaces:
- **Public REST** (`/api/v2/public/...`) — no auth needed. Used for: instruments, tickers, historical IV, OHLCV. This is what backtesting uses.
- **Private REST** (`/api/v2/private/...`) — OAuth2 client_credentials. Used for: account summary, open positions, cancel orders.
- **WebSocket** (`wss://...`) — real-time. Used for: live order placement (`private/sell`, `private/buy`), settlement subscriptions (`user.changes.any.BTC.raw`), heartbeat.

**Testnet URLs:**
- REST: `https://test.deribit.com/api/v2`
- WS: `wss://test.deribit.com/ws/api/v2`

**Mainnet URLs:**
- REST: `https://www.deribit.com/api/v2`
- WS: `wss://www.deribit.com/ws/api/v2`

Instrument naming: `BTC-25APR25-90000-P` = BTC option, expiry 25 Apr 2025, strike $90k, Put.
""")

md("### Step 20 — Write `deribit_client.py`\n\nContains: `Ticker`, `Instrument`, `AccountSummary`, `ExchangePosition` dataclasses, `DeribitPublicREST`, `DeribitPrivateREST`, `DeribitWebSocket`, `DeribitClient`.")
code(r"""%%writefile /root/Documents/btc-wheel-bot/deribit_client.py
"""
deribit_client.py — Deribit REST + WebSocket client wrapper.

Public endpoints (no auth) are used for backtest mode.
DeribitPrivateREST uses OAuth2 client_credentials for authenticated
account queries (positions, equity, settlements).
DeribitWebSocket handles real-time data, order execution, and settlement
event subscriptions for live/paper mode.

All live order methods are marked # LIVE_ONLY.
"""

from __future__ import annotations

import asyncio
import json
import time
from collections import defaultdict
from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Any, Callable

import aiohttp
import requests
from loguru import logger

from config import cfg

# ── Data models ────────────────────────────────────────────────────────────────


@dataclass
class Ticker:
    instrument_name: str
    mark_price: float
    bid: float
    ask: float
    mark_iv: float        # implied volatility (annualised %)
    delta: float
    gamma: float
    theta: float
    vega: float
    underlying_price: float
    timestamp: datetime
    greeks: dict | None = None   # raw greeks dict for easy access


@dataclass
class Instrument:
    instrument_name: str
    strike: float
    expiry_ts: int        # Unix timestamp ms
    option_type: str      # "put" | "call"
    dte: int              # days to expiry


@dataclass
class AccountSummary:
    equity: float          # total account equity in BTC
    balance: float         # cash balance in BTC
    available_funds: float # funds available for new positions
    margin_balance: float  # margin balance
    currency: str = "BTC"


@dataclass
class ExchangePosition:
    """An open position as reported by Deribit (live mode)."""
    instrument_name: str
    size: float            # positive = long, negative = short
    direction: str         # "buy" | "sell"
    average_price: float   # average entry price (BTC)
    mark_price: float
    floating_profit_loss: float
    delta: float
    option_type: str       # "put" | "call"
    expiry_ts: int


# ── REST client (public endpoints — no auth required) ─────────────────────────


class DeribitPublicREST:
    """Thin wrapper around Deribit public REST API (no authentication)."""

    BASE_URL = "https://www.deribit.com/api/v2/public"

    def __init__(self, timeout: int = 10) -> None:
        self.timeout = timeout
        self.session = requests.Session()
        self.session.headers["Accept"] = "application/json"

    def _get(self, method: str, params: dict[str, Any] | None = None) -> Any:
        """Make a GET request to a public endpoint."""
        url = f"{self.BASE_URL}/{method}"
        try:
            resp = self.session.get(url, params=params, timeout=self.timeout)
            resp.raise_for_status()
            data = resp.json()
            if "result" not in data:
                raise ValueError(f"Unexpected response: {data}")
            return data["result"]
        except requests.RequestException as exc:
            logger.error(f"REST error [{method}]: {exc}")
            raise

    def get_instruments(
        self,
        currency: str = "BTC",
        kind: str = "option",
        expired: bool = False,
    ) -> list[Instrument]:
        """Fetch all active options instruments for a currency."""
        raw = self._get("get_instruments", {
            "currency": currency,
            "kind": kind,
            "expired": str(expired).lower(),
        })
        instruments: list[Instrument] = []
        now_ts = int(time.time() * 1000)
        for item in raw:
            dte = max(0, (item["expiration_timestamp"] - now_ts) // 86_400_000)
            instruments.append(Instrument(
                instrument_name=item["instrument_name"],
                strike=float(item["strike"]),
                expiry_ts=item["expiration_timestamp"],
                option_type=item["option_type"],
                dte=dte,
            ))
        logger.debug(f"Fetched {len(instruments)} instruments for {currency}")
        return instruments

    def get_ticker(self, instrument_name: str) -> Ticker | None:
        """Fetch current ticker + Greeks for a single instrument."""
        try:
            raw = self._get("ticker", {"instrument_name": instrument_name})
            greeks_raw = raw.get("greeks", {})
            return Ticker(
                instrument_name=instrument_name,
                mark_price=float(raw.get("mark_price", 0)),
                bid=float(raw.get("best_bid_price", 0)),
                ask=float(raw.get("best_ask_price", 0)),
                mark_iv=float(raw.get("mark_iv", 0)),
                delta=float(greeks_raw.get("delta", 0)),
                gamma=float(greeks_raw.get("gamma", 0)),
                theta=float(greeks_raw.get("theta", 0)),
                vega=float(greeks_raw.get("vega", 0)),
                underlying_price=float(raw.get("underlying_price", 0)),
                timestamp=datetime.fromtimestamp(
                    raw["timestamp"] / 1000, tz=timezone.utc
                ),
                greeks=greeks_raw,
            )
        except Exception as exc:
            logger.warning(f"Could not fetch ticker for {instrument_name}: {exc}")
            return None

    def get_historical_volatility(self, currency: str = "BTC") -> list[tuple[int, float]]:
        """
        Fetch historical daily IV for a currency.
        Returns list of (timestamp_ms, iv_value) tuples.
        """
        raw = self._get("get_historical_volatility", {"currency": currency})
        return [(int(row[0]), float(row[1])) for row in raw]

    def get_tradingview_chart_data(
        self,
        instrument_name: str,
        resolution: int,
        start_timestamp: int,
        end_timestamp: int,
    ) -> list[dict[str, Any]]:
        """Fetch OHLCV data from Deribit TradingView endpoint."""
        raw = self._get("get_tradingview_chart_data", {
            "instrument_name": instrument_name,
            "start_timestamp": start_timestamp * 1000,
            "end_timestamp": end_timestamp * 1000,
            "resolution": str(resolution),
        })
        if raw.get("status") == "no_data":
            return []
        ticks   = raw.get("ticks", [])
        opens   = raw.get("open", [])
        highs   = raw.get("high", [])
        lows    = raw.get("low", [])
        closes  = raw.get("close", [])
        volumes = raw.get("volume", [])
        return [
            {
                "timestamp": ticks[i],
                "open": opens[i],
                "high": highs[i],
                "low": lows[i],
                "close": closes[i],
                "volume": volumes[i],
            }
            for i in range(len(ticks))
        ]


# ── Private REST client (authenticated) ───────────────────────────────────────


class DeribitPrivateREST:
    """
    Authenticated REST client for Deribit private endpoints.
    Uses OAuth2 client_credentials flow to obtain an access token.
    Requires DERIBIT_API_KEY and DERIBIT_API_SECRET environment variables.
    """

    def __init__(
        self,
        api_key: str,
        api_secret: str,
        testnet: bool = False,
        timeout: int = 10,
    ) -> None:
        self._api_key    = api_key
        self._api_secret = api_secret
        self._timeout    = timeout
        self._access_token: str = ""
        self._token_expires_at: float = 0.0

        base = "https://test.deribit.com" if testnet else "https://www.deribit.com"
        self._pub_url  = f"{base}/api/v2/public"
        self._priv_url = f"{base}/api/v2/private"
        self.session = requests.Session()
        self.session.headers["Accept"] = "application/json"

    def _authenticate(self) -> None:
        """Obtain an OAuth2 access token via client_credentials grant."""
        if not self._api_key or not self._api_secret:
            raise ValueError(
                "DERIBIT_API_KEY and DERIBIT_API_SECRET must be set in environment "
                "to use private REST endpoints."
            )
        url = f"{self._pub_url}/auth"
        params = {
            "grant_type": "client_credentials",
            "client_id": self._api_key,
            "client_secret": self._api_secret,
        }
        resp = self.session.get(url, params=params, timeout=self._timeout)
        resp.raise_for_status()
        data = resp.json()
        if "error" in data:
            raise RuntimeError(f"Authentication failed: {data['error']}")
        result = data["result"]
        self._access_token = result["access_token"]
        self._token_expires_at = time.time() + result.get("expires_in", 900) - 30
        logger.info("Deribit private REST authenticated (token valid ~15min)")

    def _ensure_auth(self) -> None:
        if time.time() >= self._token_expires_at:
            self._authenticate()

    def _get(self, method: str, params: dict | None = None) -> Any:
        self._ensure_auth()
        url = f"{self._priv_url}/{method}"
        headers = {"Authorization": f"Bearer {self._access_token}"}
        try:
            resp = self.session.get(
                url, params=params or {}, headers=headers, timeout=self._timeout
            )
            resp.raise_for_status()
            data = resp.json()
            if "error" in data:
                raise RuntimeError(f"Deribit API error [{method}]: {data['error']}")
            return data["result"]
        except requests.RequestException as exc:
            logger.error(f"Private REST error [{method}]: {exc}")
            raise

    def get_account_summary(self, currency: str = "BTC") -> AccountSummary:
        raw = self._get("get_account_summary", {"currency": currency})
        return AccountSummary(
            equity=float(raw.get("equity", 0.0)),
            balance=float(raw.get("balance", 0.0)),
            available_funds=float(raw.get("available_funds", 0.0)),
            margin_balance=float(raw.get("margin_balance", 0.0)),
            currency=currency,
        )

    def get_positions(self, currency: str = "BTC", kind: str = "option") -> list[ExchangePosition]:
        raw_list = self._get("get_positions", {"currency": currency, "kind": kind})
        positions: list[ExchangePosition] = []
        for raw in raw_list:
            inst = raw.get("instrument_name", "")
            parts = inst.split("-")
            opt_type = "put" if parts[-1] == "P" else "call"
            try:
                from datetime import datetime as _dt
                expiry_str = parts[1]
                expiry_dt = _dt.strptime(expiry_str, "%d%b%y").replace(
                    hour=8, minute=0, second=0, tzinfo=timezone.utc
                )
                expiry_ts = int(expiry_dt.timestamp() * 1000)
            except Exception:
                expiry_ts = 0
            positions.append(ExchangePosition(
                instrument_name=inst,
                size=float(raw.get("size", 0.0)),
                direction=raw.get("direction", "sell"),
                average_price=float(raw.get("average_price", 0.0)),
                mark_price=float(raw.get("mark_price", 0.0)),
                floating_profit_loss=float(raw.get("floating_profit_loss", 0.0)),
                delta=float(raw.get("delta", 0.0)),
                option_type=opt_type,
                expiry_ts=expiry_ts,
            ))
        return positions

    def get_open_orders(self, currency: str = "BTC", kind: str = "option") -> list[dict]:
        return self._get("get_open_orders_by_currency", {"currency": currency, "kind": kind})

    def cancel_order(self, order_id: str) -> dict:
        return self._get("cancel", {"order_id": order_id})

    def cancel_all_by_instrument(self, instrument_name: str) -> int:
        return self._get("cancel_all_by_instrument", {"instrument_name": instrument_name})


# ── WebSocket client (live/paper mode) ────────────────────────────────────────


class DeribitWebSocket:
    """
    Async WebSocket client for real-time data, order management, and
    settlement event subscriptions.
    # LIVE_ONLY — this class is NOT used in backtest mode.
    """

    def __init__(self) -> None:
        self._ws: aiohttp.ClientWebSocketResponse | None = None
        self._session: aiohttp.ClientSession | None = None
        self._msg_id: int = 1
        self._pending: dict[int, asyncio.Future] = {}
        self._authenticated: bool = False
        self._subscriptions: dict[str, Callable[[dict], None]] = {}

    async def connect(self) -> None:
        self._session = aiohttp.ClientSession()
        self._ws = await self._session.ws_connect(cfg.deribit.ws_url)
        asyncio.create_task(self._recv_loop())
        logger.info(f"WebSocket connected to {cfg.deribit.ws_url}")

    async def authenticate(self) -> None:
        if not cfg.deribit.api_key:
            raise ValueError("DERIBIT_API_KEY not set in environment")
        await self._rpc("public/auth", {
            "grant_type": "client_credentials",
            "client_id": cfg.deribit.api_key,
            "client_secret": cfg.deribit.api_secret,
        })
        self._authenticated = True
        logger.info("WebSocket authenticated")

    async def subscribe(self, channels: list[str], callback: Callable[[dict], None]) -> None:
        """Subscribe to private WebSocket channels. # LIVE_ONLY"""
        if not self._authenticated:
            raise RuntimeError("Must authenticate before subscribing to private channels")
        for channel in channels:
            self._subscriptions[channel] = callback
        result = await self._rpc("private/subscribe", {"channels": channels})
        logger.info(f"Subscribed to WebSocket channels: {channels}")
        return result

    async def _rpc(self, method: str, params: dict) -> Any:
        msg_id = self._msg_id
        self._msg_id += 1
        loop = asyncio.get_event_loop()
        fut: asyncio.Future = loop.create_future()
        self._pending[msg_id] = fut
        payload = json.dumps({
            "jsonrpc": "2.0",
            "id": msg_id,
            "method": method,
            "params": params,
        })
        await self._ws.send_str(payload)
        return await asyncio.wait_for(fut, timeout=cfg.execution.order_confirm_timeout)

    async def _recv_loop(self) -> None:
        async for msg in self._ws:
            if msg.type != aiohttp.WSMsgType.TEXT:
                continue
            try:
                data = json.loads(msg.data)
            except json.JSONDecodeError:
                continue
            if "id" in data and data["id"] in self._pending:
                fut = self._pending.pop(data["id"])
                if "error" in data:
                    fut.set_exception(RuntimeError(data["error"]["message"]))
                else:
                    fut.set_result(data.get("result"))
            elif data.get("method") == "subscription":
                params = data.get("params", {})
                channel = params.get("channel", "")
                channel_data = params.get("data", {})
                cb = self._subscriptions.get(channel)
                if cb:
                    try:
                        cb(channel_data)
                    except Exception as exc:
                        logger.error(f"Subscription callback error [{channel}]: {exc}")
                else:
                    for sub_channel, sub_cb in self._subscriptions.items():
                        if channel.startswith(sub_channel.rstrip("*")):
                            try:
                                sub_cb(channel_data)
                            except Exception as exc:
                                logger.error(f"Subscription callback error [{channel}]: {exc}")
                            break

    async def sell_option(self, instrument_name: str, amount: float,
                          order_type: str = "limit", price: float | None = None,
                          label: str = "") -> dict:
        """Place a sell order (open short position). # LIVE_ONLY"""
        if not self._authenticated:
            raise RuntimeError("Must authenticate before placing orders")
        params: dict[str, Any] = {
            "instrument_name": instrument_name,
            "amount": amount,
            "type": order_type,
            "label": label,
        }
        if price is not None:
            params["price"] = price
        result = await self._rpc("private/sell", params)
        logger.info(f"Sell order placed: {instrument_name} × {amount} @ {price}")
        return result

    async def buy_option(self, instrument_name: str, amount: float,
                         order_type: str = "limit", price: float | None = None,
                         label: str = "") -> dict:
        """Place a buy order to close a short position. # LIVE_ONLY"""
        if not self._authenticated:
            raise RuntimeError("Must authenticate before placing orders")
        params: dict[str, Any] = {
            "instrument_name": instrument_name,
            "amount": amount,
            "type": order_type,
            "label": label,
        }
        if price is not None:
            params["price"] = price
        result = await self._rpc("private/buy", params)
        logger.info(f"Buy-to-close order placed: {instrument_name} × {amount} @ {price}")
        return result

    async def close(self) -> None:
        if self._ws and not self._ws.closed:
            await self._ws.close()
        if self._session and not self._session.closed:
            await self._session.close()
        logger.info("WebSocket connection closed")


# ── Combined client ────────────────────────────────────────────────────────────


class DeribitClient:
    """Unified Deribit client — public REST, private REST, and WebSocket."""

    def __init__(self) -> None:
        self.rest = DeribitPublicREST(timeout=cfg.deribit.request_timeout)
        self.ws: DeribitWebSocket | None = None
        self._private: DeribitPrivateREST | None = None
        if cfg.deribit.api_key and cfg.deribit.api_secret:
            self._private = DeribitPrivateREST(
                api_key=cfg.deribit.api_key,
                api_secret=cfg.deribit.api_secret,
                testnet=cfg.deribit.testnet,
                timeout=cfg.deribit.request_timeout,
            )
            logger.info("DeribitPrivateREST initialised (API keys found)")
        else:
            logger.info(
                "No DERIBIT_API_KEY/SECRET — private REST unavailable; "
                "running in public-only mode (paper trading with simulated state)"
            )

    @property
    def private(self) -> DeribitPrivateREST | None:
        return self._private

    def has_private_access(self) -> bool:
        return self._private is not None

    async def connect_live(self) -> None:
        self.ws = DeribitWebSocket()
        await self.ws.connect()
        await self.ws.authenticate()

    async def disconnect(self) -> None:
        if self.ws:
            await self.ws.close()
""")

md("### Step 21 — Test: REST connection to Deribit public API")
code("""import sys; sys.path.insert(0, "/root/Documents/btc-wheel-bot")
import os; os.chdir("/root/Documents/btc-wheel-bot")
from deribit_client import DeribitPublicREST

rest = DeribitPublicREST(timeout=10)

# Fetch BTC spot price
price_data = rest._get("get_index_price", {"index_name": "btc_usd"})
btc_price = price_data["index_price"]
print(f"BTC spot price: ${btc_price:,.0f}")
assert btc_price > 1000, "BTC price looks wrong"

# Fetch some instruments
instruments = rest.get_instruments(currency="BTC")
puts = [i for i in instruments if i.option_type == "put"]
print(f"Total BTC options: {len(instruments)}")
print(f"Put options: {len(puts)}")
assert len(puts) > 0, "No puts found"
print("CHECKPOINT: Deribit REST connection OK")
""")

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 3: Strategy
# ─────────────────────────────────────────────────────────────────────────────
md("## Phase 3: Strategy Logic (Steps 22–36)")

md("""### Step 22 — The Wheel Strategy concept

The **options wheel** is a premium-collection strategy:

1. **Sell a cash-secured put** at a delta ~0.20–0.40 (OTM).
   - Collect premium upfront.
   - If BTC stays above strike → option expires worthless, keep premium. ✓
   - If BTC falls below strike → option expires ITM, "assigned" (on Deribit, cash-settled).

2. **Sell a covered call** after put cycle completes.
   - If put expired OTM → sell a normal call at delta ~0.25.
   - If put expired ITM ("recovery mode") → sell a call at or above the put strike
     so any BTC recovery above that level is captured.

3. **Repeat** — put → call → put → ...

**Key filters:**
- IV rank ≥ threshold (only sell when options are "expensive")
- Dynamic delta: high IV rank → sell closer ATM (more premium), low IV rank → sell further OTM (safer)
- Regime filter (optional): only sell puts when BTC is above its N-day SMA
- Ladder mode (optional): N puts at evenly-spaced delta targets simultaneously
""")

md("### Step 23 — Write `strategy.py`")
code(r"""%%writefile /root/Documents/btc-wheel-bot/strategy.py
"""
strategy.py — Core wheel strategy logic.

Responsibilities:
  - Calculate IV rank from historical volatility series
  - Select the best strike given a target delta range and cycle (put/call)
  - Decide whether to open a new position based on IV rank threshold
  - Determine the next cycle direction (put → call → put ...)
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Literal

import numpy as np
from loguru import logger

from config import cfg
from deribit_client import DeribitPublicREST, Instrument, Ticker

Cycle = Literal["put", "call"]


@dataclass
class StrikeCandidate:
    instrument: Instrument
    ticker: Ticker
    score: float          # higher = preferred


@dataclass
class OpenSignal:
    """Returned when strategy decides to open a position."""
    instrument_name: str
    strike: float
    option_type: str
    expiry_ts: int
    dte: int
    delta: float
    mark_iv: float
    mark_price: float
    underlying_price: float
    cycle: Cycle
    iv_rank: float


class WheelStrategy:
    """
    Implements the BTC options wheel premium-collection strategy.

    Flow:
        1. calculate_iv_rank()  → is now a good time to sell?
        2. decide_cycle()       → sell put or call?
        3. select_strike()      → which strike to target?
        4. generate_signal()    → combine all into an OpenSignal (or None)
    """

    def __init__(self, rest_client: DeribitPublicREST) -> None:
        self._rest = rest_client
        self._current_cycle: Cycle = cfg.strategy.initial_cycle
        self._put_cycle_complete: bool = False
        self._last_put_was_itm: bool = False
        self._last_put_strike: float = 0.0

    def calculate_iv_rank(self, iv_history: list[tuple[int, float]]) -> float:
        """
        Calculate IV rank (0–1) over a 52-week rolling window.
        IV rank = (current_iv - 52w_low) / (52w_high - 52w_low)
        Returns 0.0 if insufficient data.
        """
        if len(iv_history) < 2:
            logger.warning("Insufficient IV history for rank calculation")
            return 0.0
        recent = iv_history[-365:]
        values = [v for _, v in recent]
        current_iv = values[-1]
        low_52w = min(values)
        high_52w = max(values)
        if high_52w == low_52w:
            return 0.5
        rank = (current_iv - low_52w) / (high_52w - low_52w)
        logger.debug(f"IV rank: {rank:.2%} (current={current_iv:.1f}, "
                     f"low={low_52w:.1f}, high={high_52w:.1f})")
        return round(float(np.clip(rank, 0.0, 1.0)), 4)

    def decide_cycle(self, last_cycle: Cycle | None = None) -> Cycle:
        """Alternate put → call → put. Pass last_cycle to override."""
        if last_cycle is None:
            last_cycle = self._current_cycle
        next_cycle: Cycle = "call" if last_cycle == "put" else "put"
        self._current_cycle = next_cycle
        logger.debug(f"Cycle decision: {last_cycle} → {next_cycle}")
        return next_cycle

    def select_strike(
        self,
        instruments: list[Instrument],
        tickers: dict[str, Ticker],
        cycle: Cycle,
        underlying_price: float,
        iv_rank: float = 0.5,
        delta_target_override: float | None = None,
        recovery_min_strike: float | None = None,
    ) -> StrikeCandidate | None:
        """
        Select the best-scoring option strike within the target delta range.

        Scoring formula: 0.7 × delta_score + 0.3 × iv_score

        Dynamic delta (iv_dynamic_delta=True):
          target_mid = d_min + (d_max - d_min) × iv_rank
          Low IV rank → conservative (far OTM).
          High IV rank → aggressive (closer ATM, more premium).

        Recovery mode: only call strikes ≥ recovery_min_strike.
        """
        d_min = cfg.strategy.target_delta_min
        d_max = cfg.strategy.target_delta_max

        if delta_target_override is not None:
            target_delta_mid = float(np.clip(delta_target_override, d_min, d_max))
        elif cfg.strategy.iv_dynamic_delta:
            target_delta_mid = d_min + (d_max - d_min) * float(np.clip(iv_rank, 0.0, 1.0))
            logger.debug(
                f"Dynamic delta: IV rank={iv_rank:.2%} → "
                f"target mid={target_delta_mid:.4f}"
            )
        else:
            target_delta_mid = (d_min + d_max) / 2.0

        candidates: list[StrikeCandidate] = []

        for inst in instruments:
            if inst.option_type != cycle:
                continue
            if not (cfg.strategy.min_dte <= inst.dte <= cfg.strategy.max_dte):
                continue
            ticker = tickers.get(inst.instrument_name)
            if ticker is None or ticker.mark_price <= 0:
                continue
            delta_abs = abs(ticker.delta)
            if not (cfg.strategy.target_delta_min <= delta_abs <= cfg.strategy.target_delta_max):
                continue
            if ticker.bid <= 0:
                continue
            if recovery_min_strike is not None and cycle == "call":
                if inst.strike < recovery_min_strike:
                    continue

            delta_score = 1.0 - abs(delta_abs - target_delta_mid) / target_delta_mid
            iv_score = min(ticker.mark_iv / 100.0, 1.0)
            score = 0.7 * delta_score + 0.3 * iv_score

            candidates.append(StrikeCandidate(
                instrument=inst,
                ticker=ticker,
                score=score,
            ))

        if not candidates:
            logger.warning(
                f"No qualifying {cycle} strikes found "
                f"(delta {cfg.strategy.target_delta_min}–{cfg.strategy.target_delta_max}, "
                f"DTE {cfg.strategy.min_dte}–{cfg.strategy.max_dte})"
            )
            return None

        candidates.sort(key=lambda c: c.score, reverse=True)
        best = candidates[0]
        logger.info(
            f"Selected strike: {best.instrument.instrument_name} | "
            f"delta={best.ticker.delta:.3f} | IV={best.ticker.mark_iv:.1f}% | "
            f"mark={best.ticker.mark_price:.4f} BTC | score={best.score:.3f}"
        )
        return best

    def select_ladder_strikes(
        self,
        instruments: list[Instrument],
        tickers: dict[str, Ticker],
        underlying_price: float,
        n_legs: int,
        iv_rank: float = 0.5,
    ) -> list[StrikeCandidate]:
        """
        Select N put strike candidates at evenly-spaced delta targets.

        For n_legs=2 with delta [0.15, 0.39]:
          Leg 1: target delta ≈ 0.24 (conservative — far OTM)
          Leg 2: target delta ≈ 0.33 (aggressive — closer ATM)

        Targets at position (k+1)/(n+1) within [d_min, d_max].
        Duplicate strikes excluded.
        """
        d_min = cfg.strategy.target_delta_min
        d_max = cfg.strategy.target_delta_max
        targets = [
            d_min + (d_max - d_min) * (k + 1) / (n_legs + 1)
            for k in range(n_legs)
        ]
        results: list[StrikeCandidate] = []
        used_strikes: set[float] = set()

        for target in targets:
            candidate = self.select_strike(
                instruments=instruments,
                tickers=tickers,
                cycle="put",
                underlying_price=underlying_price,
                iv_rank=iv_rank,
                delta_target_override=target,
            )
            if candidate is None:
                continue
            if candidate.instrument.strike in used_strikes:
                logger.debug(f"Ladder: skipping duplicate strike {candidate.instrument.strike:,.0f}")
                continue
            used_strikes.add(candidate.instrument.strike)
            results.append(candidate)
            logger.info(
                f"Ladder leg {len(results)}/{n_legs}: "
                f"{candidate.instrument.instrument_name} "
                f"delta_tgt={target:.3f} actual={candidate.ticker.delta:.3f}"
            )

        return results

    def generate_signal(
        self,
        iv_history: list[tuple[int, float]],
        instruments: list[Instrument],
        tickers: dict[str, Ticker],
        underlying_price: float,
        last_cycle: Cycle | None = None,
    ) -> OpenSignal | None:
        """
        Full strategy pass: IV rank check → cycle → strike → signal.
        Returns OpenSignal if conditions are met, None otherwise.
        """
        # Step 1: IV rank filter
        iv_rank = self.calculate_iv_rank(iv_history)
        if iv_rank < cfg.strategy.iv_rank_threshold:
            logger.info(
                f"IV rank {iv_rank:.2%} below threshold "
                f"{cfg.strategy.iv_rank_threshold:.2%} — skipping"
            )
            return None

        # Step 2: Cycle decision
        cycle = self.decide_cycle(last_cycle)

        # Wheel guard: only sell call after put leg completed
        if cycle == "call" and not self._put_cycle_complete:
            logger.info("Wheel guard: put leg not yet complete — staying in put-selling mode")
            cycle = "put"
            self._current_cycle = "put"

        # Recovery call mode
        recovery_min_strike: float | None = None
        if cycle == "call" and self._last_put_was_itm and self._last_put_strike > 0:
            recovery_min_strike = self._last_put_strike
            logger.info(
                f"Recovery call mode: targeting strikes ≥ ${recovery_min_strike:,.0f}"
            )

        # Step 3: Strike selection
        candidate = self.select_strike(
            instruments, tickers, cycle, underlying_price,
            iv_rank=iv_rank,
            recovery_min_strike=recovery_min_strike,
        )
        if candidate is None:
            return None

        return OpenSignal(
            instrument_name=candidate.instrument.instrument_name,
            strike=candidate.instrument.strike,
            option_type=cycle,
            expiry_ts=candidate.instrument.expiry_ts,
            dte=candidate.instrument.dte,
            delta=candidate.ticker.delta,
            mark_iv=candidate.ticker.mark_iv,
            mark_price=candidate.ticker.mark_price,
            underlying_price=underlying_price,
            cycle=cycle,
            iv_rank=iv_rank,
        )
""")

md("### Step 24 — Test: IV rank calculation")
code("""from strategy import WheelStrategy
from deribit_client import DeribitPublicREST

rest = DeribitPublicREST()
strat = WheelStrategy(rest)

# Fetch real IV history
iv_history = rest.get_historical_volatility("BTC")
print(f"IV history points: {len(iv_history)}")

iv_rank = strat.calculate_iv_rank(iv_history)
print(f"Current IV rank: {iv_rank:.2%}")
assert 0.0 <= iv_rank <= 1.0, "IV rank out of range"
print("Strategy IV rank: OK")
""")

md("### Step 25 — CHECKPOINT: strategy signal generation")
code("""from strategy import WheelStrategy
from deribit_client import DeribitPublicREST
import time

rest = DeribitPublicREST()
strat = WheelStrategy(rest)

iv_history = rest.get_historical_volatility("BTC")
instruments = rest.get_instruments("BTC")

# Fetch a sample of tickers
dte_min = 3; dte_max = 37
candidates = [i for i in instruments if dte_min <= i.dte <= dte_max][:20]
tickers = {}
for inst in candidates:
    t = rest.get_ticker(inst.instrument_name)
    if t:
        tickers[inst.instrument_name] = t
    time.sleep(0.05)  # rate limit courtesy

underlying = next(iter(tickers.values())).underlying_price if tickers else 80000.0
print(f"BTC price: ${underlying:,.0f}")

signal = strat.generate_signal(iv_history, instruments, tickers, underlying)
if signal:
    print(f"Signal: {signal.instrument_name} | delta={signal.delta:.3f} | IV rank={signal.iv_rank:.2%}")
else:
    iv_rank = strat.calculate_iv_rank(iv_history)
    print(f"No signal (IV rank {iv_rank:.2%} may be below threshold {strat._cfg_threshold:.2%})")
    # This is expected when IV rank is low — not a bug
    
print("Phase 3 CHECKPOINT PASSED")
""")

# ─────────────────────────────────────────────────────────────────────────────
# PHASE 4: Risk Manager
# ─────────────────────────────────────────────────────────────────────────────
md("## Phase 4: Risk Manager (Steps 26–38)")

md("### Step 26 — Write `risk_manager.py`\n\nAll checks return `True` (safe) or `False` (block). Fail-fast design: any False stops the trade.")
code(r"""%%writefile /root/Documents/btc-wheel-bot/risk_manager.py
"""
risk_manager.py — Position sizing and risk controls.
All checks return True = safe to proceed, False = halt/roll.
"""

from __future__ import annotations

import math
import os
from dataclasses import dataclass
from pathlib import Path

from loguru import logger

from config import cfg


@dataclass
class Position:
    instrument_name: str
    strike: float
    option_type: str           # "put" | "call"
    entry_price: float         # premium received (BTC per contract)
    underlying_at_entry: float # spot price when sold
    contracts: float           # number of contracts
    current_delta: float       # current absolute delta
    current_price: float       # current mark price (BTC)
    entry_equity: float        # account equity at time of entry
    expiry_ts: int = 0         # Deribit expiry timestamp (ms)
    iv_rank_at_entry: float = 0.0
    dte_at_entry: int = 0


class RiskManager:
    """
    Enforces all risk rules before and during position lifecycle.

    Pre-trade checks (call before opening):
        check_kill_switch()
        check_max_legs()
        check_position_size()
        check_collateral()
        check_free_margin()

    In-trade checks (call on each poll):
        should_roll()
        check_drawdown()
    """

    def __init__(self) -> None:
        self._kill_switch_path = Path(cfg.risk.kill_switch_file)

    # ── Pre-trade ─────────────────────────────────────────────────────────────

    def check_kill_switch(self) -> bool:
        """Return False (block trading) if KILL_SWITCH file exists."""
        if self._kill_switch_path.exists():
            logger.critical(
                f"KILL SWITCH ACTIVE — file '{cfg.risk.kill_switch_file}' found. "
                "All trading halted. Delete the file to resume."
            )
            return False
        return True

    def check_max_legs(self, open_positions: list[Position]) -> bool:
        """Block new positions if at maximum open legs."""
        if len(open_positions) >= cfg.sizing.max_open_legs:
            logger.info(
                f"Max open legs reached ({cfg.sizing.max_open_legs}). "
                "Skipping new position."
            )
            return False
        return True

    def calculate_contracts(
        self,
        equity_usd: float,
        strike_usd: float,
        equity_fraction: float | None = None,
    ) -> float:
        """
        Calculate contracts to sell given equity and strike.

        On Deribit: 1 contract = 1 BTC notional, minimum lot = 0.1 BTC.
        Collateral per contract = strike_usd (full notional).

        equity_fraction: override max_equity_per_leg (used by ladder to split evenly).
        Returns number of contracts floored to nearest 0.1.
        """
        if strike_usd <= 0 or equity_usd <= 0:
            return 0.0
        fraction = equity_fraction if equity_fraction is not None else cfg.sizing.max_equity_per_leg
        max_notional = equity_usd * fraction
        collateral_per_contract = strike_usd
        raw_contracts = max_notional / collateral_per_contract
        min_lot = cfg.sizing.contract_size_btc  # 0.1
        contracts = max(min_lot, math.floor(raw_contracts / min_lot) * min_lot)
        logger.debug(
            f"Sizing: equity=${equity_usd:,.0f}, strike=${strike_usd:,.0f}, "
            f"max_notional=${max_notional:,.0f} → {contracts} contracts"
        )
        return contracts

    def check_position_size(self, equity_usd: float, strike_usd: float) -> bool:
        """Return True if at least 0.1 contracts can be sized from current equity."""
        if strike_usd <= 0 or equity_usd <= 0:
            return False
        max_notional = equity_usd * cfg.sizing.max_equity_per_leg
        collateral_per_contract = strike_usd
        if collateral_per_contract <= 0:
            return False
        raw_contracts = max_notional / collateral_per_contract
        if raw_contracts < 0.1:
            logger.warning(
                f"Position too small: {raw_contracts:.4f} raw contracts at strike "
                f"${strike_usd:,.0f}. Equity ${equity_usd:,.0f} too low."
            )
            return False
        return True

    def check_collateral(
        self, open_positions: list[Position], equity_usd: float, btc_price: float
    ) -> bool:
        """
        Verify total collateral exposure does not exceed the buffer limit.
        Collateral used = sum(strike × contracts × contract_size) for each put.
        Buffer limit = equity × collateral_buffer.
        """
        if not open_positions:
            return True
        total_collateral = sum(
            pos.strike * pos.contracts * cfg.sizing.contract_size_btc
            for pos in open_positions
        )
        max_allowed = equity_usd * cfg.sizing.collateral_buffer
        if total_collateral > max_allowed:
            logger.warning(
                f"Collateral check FAILED: ${total_collateral:,.0f} used "
                f"vs ${max_allowed:,.0f} allowed"
            )
            return False
        logger.debug(f"Collateral OK: ${total_collateral:,.2f} / ${max_allowed:,.2f}")
        return True

    def check_free_margin(
        self,
        equity_usd: float,
        open_positions: list[Position],
        proposed_strike_usd: float,
        proposed_contracts: float,
    ) -> bool:
        """
        Verify opening a new leg leaves enough free (unreserved) capital.

        Calculation:
            reserved_now  = Σ(strike × contracts × contract_size) for existing legs
            reserved_new  = proposed_strike × proposed_contracts × contract_size
            free_after    = equity - reserved_now - reserved_new
            required_free = equity × min_free_equity_fraction
        """
        threshold = cfg.sizing.min_free_equity_fraction
        if threshold <= 0.0:
            return True
        reserved_now = sum(
            pos.strike * pos.contracts * cfg.sizing.contract_size_btc
            for pos in open_positions
        )
        reserved_new  = proposed_strike_usd * proposed_contracts * cfg.sizing.contract_size_btc
        free_after    = equity_usd - reserved_now - reserved_new
        required_free = equity_usd * threshold
        if free_after < required_free:
            logger.warning(
                f"Free-margin check FAILED: ${free_after:,.0f} free after proposed leg "
                f"(need ≥ ${required_free:,.0f} = {threshold:.0%} of equity)."
            )
            return False
        logger.debug(f"Free-margin OK: ${free_after:,.0f} free after leg")
        return True

    # ── In-trade ──────────────────────────────────────────────────────────────

    def should_roll(self, position: Position) -> tuple[bool, str]:
        """
        Check if an open position should be rolled or closed.
        Returns (should_roll: bool, reason: str).
        Reasons: "delta_breach", "loss_breach", "ok"
        """
        if abs(position.current_delta) > cfg.risk.max_adverse_delta:
            logger.warning(
                f"Delta breach on {position.instrument_name}: "
                f"|delta|={abs(position.current_delta):.3f} > {cfg.risk.max_adverse_delta}"
            )
            return True, "delta_breach"

        premium_received = position.entry_price * position.contracts
        current_cost = position.current_price * position.contracts
        unrealised_pnl_btc = premium_received - current_cost
        unrealised_pnl_usd = unrealised_pnl_btc * position.underlying_at_entry
        loss_pct = -unrealised_pnl_usd / position.entry_equity

        if loss_pct > cfg.risk.max_loss_per_leg:
            logger.warning(
                f"Loss breach on {position.instrument_name}: "
                f"loss={loss_pct:.2%} > {cfg.risk.max_loss_per_leg:.2%}"
            )
            return True, "loss_breach"

        return False, "ok"

    def check_drawdown(self, equity_curve: list[float]) -> bool:
        """
        Check daily drawdown from peak equity.
        Returns False (halt trading) if drawdown exceeds threshold.
        """
        if len(equity_curve) < 2:
            return True
        peak = max(equity_curve)
        current = equity_curve[-1]
        drawdown = (peak - current) / peak
        if drawdown > cfg.risk.max_daily_drawdown:
            logger.error(
                f"Drawdown limit breached: {drawdown:.2%} > "
                f"{cfg.risk.max_daily_drawdown:.2%}. Trading paused."
            )
            return False
        logger.debug(f"Drawdown OK: {drawdown:.2%}")
        return True

    def full_pre_trade_check(
        self,
        open_positions: list[Position],
        equity_usd: float,
        strike_usd: float,
        btc_price: float,
        proposed_contracts: float | None = None,
    ) -> bool:
        """
        Run all pre-trade checks in sequence.
        Returns True only if every check passes.
        """
        if proposed_contracts is None:
            proposed_contracts = self.calculate_contracts(equity_usd, strike_usd)

        checks = [
            self.check_kill_switch(),
            self.check_max_legs(open_positions),
            self.check_position_size(equity_usd, strike_usd),
            self.check_collateral(open_positions, equity_usd, btc_price),
            self.check_free_margin(equity_usd, open_positions, strike_usd, proposed_contracts),
        ]
        result = all(checks)
        if result:
            logger.info("Pre-trade checks PASSED")
        else:
            logger.warning("Pre-trade checks FAILED — position not opened")
        return result
""")

md("### Step 27 — Test: risk manager pre-trade checks")
code("""from risk_manager import RiskManager, Position

rm = RiskManager()
equity = 50_000.0  # $50k account
strike = 80_000.0  # $80k BTC put
btc_price = 85_000.0

# No positions — should pass
result = rm.full_pre_trade_check(
    open_positions=[],
    equity_usd=equity,
    strike_usd=strike,
    btc_price=btc_price,
)
print(f"Empty positions check: {'PASS' if result else 'FAIL'}")

# Contract sizing
contracts = rm.calculate_contracts(equity, strike)
print(f"Contracts: {contracts}")
assert contracts >= 0.1, "Should size at least 0.1 contracts"

# Drawdown check
equity_curve = [50000, 49000, 48000, 47000]
dd_ok = rm.check_drawdown(equity_curve)
print(f"Drawdown check ($50k→$47k): {'PASS' if dd_ok else 'FAIL — halted'}")
print("Phase 4 CHECKPOINT PASSED")
""")

print("Script part 1 complete, building cells list continued below...")

# Write the notebook so far
nb.cells = cells

with open("/sessions/keen-eloquent-cray/mnt/Documents/btc-wheel-bot/btc_wheel_bot_reconstruction_guide.ipynb", "w") as f:
    nbformat.write(nb, f)

print(f"Notebook written with {len(cells)} cells so far")
